### ISSUE TITLE
productVersion "2.9.0" is coming in annotations of deployments after upgrade from 2.9.0 to 2.10.0 

### ISSUE THREAD

**Issue by saurabhwani5** [IBM/ibm-spectrum-scale-csi#1035]
## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. Install CSI 2.9.0 :
```
[OCP ~]# oc get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-9ngd9                          3/3     Running   0          12s
ibm-spectrum-scale-csi-attacher-7dff5546c9-j22wr      1/1     Running   0          12s
ibm-spectrum-scale-csi-attacher-7dff5546c9-t9w77      1/1     Running   0          12s
ibm-spectrum-scale-csi-b5f9b                          3/3     Running   0          12s
ibm-spectrum-scale-csi-k48qf                          3/3     Running   0          12s
ibm-spectrum-scale-csi-operator-c45564f-msgzx         1/1     Running   0          86s
ibm-spectrum-scale-csi-provisioner-6ff98cc858-gm2rg   1/1     Running   0          12s
ibm-spectrum-scale-csi-resizer-f45dd65f7-7k9wn        1/1     Running   0          12s
ibm-spectrum-scale-csi-snapshotter-74d845c99b-qp7r8   1/1     Running   0          12s
[OCP ~]# oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.9.0     True
[OCP ~]# oc describe pod | grep quay
    Image:         quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
    Image ID:      quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
  Normal  Pulling    21s   kubelet            Pulling image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7"
  Normal  Pulled     13s   kubelet            Successfully pulled image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7" in 7.508695104s (7.508715135s including waiting)
    Image:         quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
    Image ID:      quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
  Normal  Pulling    20s   kubelet            Pulling image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7"
  Normal  Pulled     13s   kubelet            Successfully pulled image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7" in 7.32483806s (7.324849171s including waiting)
    Image:         quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
    Image ID:      quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
  Normal  Pulling    21s   kubelet            Pulling image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7"
  Normal  Pulled     13s   kubelet            Successfully pulled image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7" in 7.578392131s (7.578403411s including waiting)
    Image:         quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator@sha256:da7ada19c06b20edc9b3c8067a8380f6879899022dda8a5c1cbed7c15b2a381d
    Image ID:      quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator@sha256:36f410d228bd5329444ed82e17ad996103f166aad58db2a17b4fa5ce2601db15
      CSI_DRIVER_IMAGE:          quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
  Normal  Pulling    94s   kubelet            Pulling image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator@sha256:da7ada19c06b20edc9b3c8067a8380f6879899022dda8a5c1cbed7c15b2a381d"
  Normal  Pulled     88s   kubelet            Successfully pulled image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator@sha256:da7ada19c06b20edc9b3c8067a8380f6879899022dda8a5c1cbed7c15b2a381d" in 6.186327979s (6.18634801s including waiting)
```
  
2. Upgrade to 2.10.0 RC1 :
```
[OCP annotation]# oc get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-attacher-5bd7bc8569-5lw4b      1/1     Running   0          4m15s
ibm-spectrum-scale-csi-attacher-5bd7bc8569-st9z4      1/1     Running   0          4m15s
ibm-spectrum-scale-csi-operator-8568d74b64-fwjbc      1/1     Running   0          4m35s
ibm-spectrum-scale-csi-pbhxj                          3/3     Running   0          4m11s
ibm-spectrum-scale-csi-provisioner-6cbb75b74-gf975    1/1     Running   0          4m15s
ibm-spectrum-scale-csi-q8qsl                          3/3     Running   0          4m14s
ibm-spectrum-scale-csi-resizer-75467db98f-vq2s8       1/1     Running   0          4m15s
ibm-spectrum-scale-csi-snapshotter-5f77874594-dnzxh   1/1     Running   0          4m15s
ibm-spectrum-scale-csi-x22bl                          3/3     Running   0          4m9s
[OCP annotation]# oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.10.0    True
[OCP annotation]# oc describe pod | grep quay
    Image:         quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator:v2.10.0-220923
    Image ID:      quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:52a24a97a9ad649603c8708d874c538fc22ef067767761fef9ffae091846695e
      CSI_DRIVER_IMAGE:          quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.10.0-220923
  Normal  Pulled          4m43s  kubelet            Container image "quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator:v2.10.0-220923" already present on machine
    Image:         quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.10.0-220923
    Image ID:      quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:05837457d22e79593aa476f61374e640b9762e3e53b57b433d08140de70be96d
  Normal  Pulled     4m20s  kubelet            Container image "quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.10.0-220923" already present on machine
    Image:         quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.10.0-220923
    Image ID:      quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:05837457d22e79593aa476f61374e640b9762e3e53b57b433d08140de70be96d
  Normal  Pulled     4m22s  kubelet            Container image "quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.10.0-220923" already present on machine
    Image:         quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.10.0-220923
    Image ID:      quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:05837457d22e79593aa476f61374e640b9762e3e53b57b433d08140de70be96d
  Normal  Pulled     4m18s  kubelet            Container image "quay.
```
3. Check the annotations of deployment :
```
[OCP ~]# oc get deployment
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
ibm-spectrum-scale-csi-attacher      2/2     2            2           94m
ibm-spectrum-scale-csi-operator      1/1     1            1           3d7h
ibm-spectrum-scale-csi-provisioner   1/1     1            1           94m
ibm-spectrum-scale-csi-resizer       1/1     1            1           94m
ibm-spectrum-scale-csi-snapshotter   1/1     1            1           94m
[OCP ~]# oc edit deployment ibm-spectrum-scale-csi-attacher
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    productID: ibm-spectrum-scale-csi-operator
    productName: IBM Spectrum Scale CSI Operator
    productVersion: 2.9.0
[OCP ~]# oc edit deployment ibm-spectrum-scale-csi-provisionerapiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    productID: ibm-spectrum-scale-csi-operator
    productName: IBM Spectrum Scale CSI Operator
    productVersion: 2.9.0
[OCP ~]# oc edit deployment ibm-spectrum-scale-csi-resizer
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    productID: ibm-spectrum-scale-csi-operator
    productName: IBM Spectrum Scale CSI Operator
    productVersion: 2.9.0
  creationTimestamp: "2023-09-28T11:38:31Z"
[OCP ~]# oc edit deployment ibm-spectrum-scale-csi-snapshotter
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    productID: ibm-spectrum-scale-csi-operator
    productName: IBM Spectrum Scale CSI Operator
    productVersion: 2.9.0
  creationTimestamp: "2023-09-28T11:38:31Z"
```

## Expected behavior
Annotations should be 2.10.0 

Must Gather :
scale-csi/D.1035
