### ISSUE TITLE
volume snapshot is not getting deleted for version 2 volumes in shallow copy 

### ISSUE THREAD

**Issue by saurabhwani5** [IBM/ibm-spectrum-scale-csi#1082]
## Describe the bug
When we take two snapshots of version 2 pvc and try to delete the one of the  created snapshot in that case it is not getting deleted for shallow copy images 

## How to Reproduce?

1. Install CSI 2.11.0 with #1067  driver images :
```
[ocp csi-tools]# oc get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-47f2t                          3/3     Running   0          4m56s
ibm-spectrum-scale-csi-attacher-585ddbd6bb-mtldd      1/1     Running   0          5m7s
ibm-spectrum-scale-csi-attacher-585ddbd6bb-v4s69      1/1     Running   0          5m7s
ibm-spectrum-scale-csi-ctjlp                          3/3     Running   0          4m56s
ibm-spectrum-scale-csi-jjbnj                          3/3     Running   0          4m56s
ibm-spectrum-scale-csi-operator-787646b4fc-57wgp      1/1     Running   0          5m57s
ibm-spectrum-scale-csi-provisioner-765d779f6b-8kvtz   1/1     Running   0          5m7s
ibm-spectrum-scale-csi-resizer-644c7bd59b-wc9gz       1/1     Running   0          5m7s
ibm-spectrum-scale-csi-snapshotter-7cd97548d5-bxdvf   1/1     Running   0          5m7s
[ocp csi-tools]# oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.11.0    True
[ocp csi-tools]# oc describe pod | grep quay
    Image:         quay.io/hemalatha_gajendran/driver_shallowcopy_validation:latest
    Image ID:      quay.io/hemalatha_gajendran/driver_shallowcopy_validation@sha256:6edee46866763eaf3a0bc5f5bed8e478ef3679ce6c2ed4076a812b89b6136435
  Normal  Pulling    5m17s  kubelet            Pulling image "quay.io/hemalatha_gajendran/driver_shallowcopy_validation:latest"
  Normal  Pulled     5m13s  kubelet            Successfully pulled image "quay.io/hemalatha_gajendran/driver_shallowcopy_validation:latest" in 3.926581487s (3.926595877s including waiting)
    Image:         quay.io/hemalatha_gajendran/driver_shallowcopy_validation:latest
    Image ID:      quay.io/hemalatha_gajendran/driver_shallowcopy_validation@sha256:6edee46866763eaf3a0bc5f5bed8e478ef3679ce6c2ed4076a812b89b6136435
  Normal  Pulling    5m17s  kubelet            Pulling image "quay.io/hemalatha_gajendran/driver_shallowcopy_validation:latest"
  Normal  Pulled     5m14s  kubelet            Successfully pulled image "quay.io/hemalatha_gajendran/driver_shallowcopy_validation:latest" in 2.981190564s (2.981214406s including waiting)
    Image:         quay.io/hemalatha_gajendran/driver_shallowcopy_validation:latest
    Image ID:      quay.io/hemalatha_gajendran/driver_shallowcopy_validation@sha256:6edee46866763eaf3a0bc5f5bed8e478ef3679ce6c2ed4076a812b89b6136435
  Normal  Pulling    5m17s  kubelet            Pulling image "quay.io/hemalatha_gajendran/driver_shallowcopy_validation:latest"
  Normal  Pulled     5m12s  kubelet            Successfully pulled image "quay.io/hemalatha_gajendran/driver_shallowcopy_validation:latest" in 4.243327618s (4.243358469s including waiting)
    Image:         quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:18264e0c9c112856bc2744f7f971a4b60ecb24de57e46af4d35456dcdf8e3cbf
    Image ID:      quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:18264e0c9c112856bc2744f7f971a4b60ecb24de57e46af4d35456dcdf8e3cbf
      CSI_DRIVER_IMAGE:          quay.io/hemalatha_gajendran/driver_shallowcopy_validation:latest
  Normal  Pulled          6m18s  kubelet            Container image "quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:18264e0c9c112856bc2744f7f971a4b60ecb24de57e46af4d35456dcdf8e3cbf" already present on machine
```
2. Create version 2 PVC :
[ocp ]# cat apply.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scale-advance-pvc-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibm-spectrum-scale-csi-advance

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-advance
provisioner: spectrumscale.csi.ibm.com
parameters:
   volBackendFs: "fs0"
   version: "2"
reclaimPolicy: Delete
[ocp ]# oc apply -f apply.yaml
persistentvolumeclaim/scale-advance-pvc-1 created
storageclass.storage.k8s.io/ibm-spectrum-scale-csi-advance created
[ocp ]# oc get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                     AGE
scale-advance-pvc-1   Bound    pvc-81b65bbb-6ef7-49be-bed0-ab0ced03dcfb   1Gi        RWX            ibm-spectrum-scale-csi-advance   102s
```
3. Take snapshot of PVC :
```
[ocp ]# cat snapshot.yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ibm-spectrum-scale-snapshot-1
spec:
  volumeSnapshotClassName: ibm-spectrum-scale-snapshotclass-advance
  source:
    persistentVolumeClaimName: scale-advance-pvc-1
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ibm-spectrum-scale-snapshotclass-advance
driver: spectrumscale.csi.ibm.com
parameters:
  snapWindow: "30"  #Optional : Time in minutes (default=30)
deletionPolicy: Delete
[ocp ]# oc apply -f snapshot.yaml
volumesnapshot.snapshot.storage.k8s.io/ibm-spectrum-scale-snapshot-1 created
volumesnapshotclass.snapshot.storage.k8s.io/ibm-spectrum-scale-snapshotclass-advance created
[ocp ]# oc get vs
NAME                            READYTOUSE   SOURCEPVC             SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS                              SNAPSHOTCONTENT                                    CREATIONTIME   AGE
ibm-spectrum-scale-snapshot-1   true         scale-advance-pvc-1                           1Gi           ibm-spectrum-scale-snapshotclass-advance   snapcontent-852bbcb2-ce98-408b-8346-4bfa04c64cb7   20s            37s
```

4. Take one more snapshot of same PVC :
```
[ocp ]# cat snapshot1.yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ibm-spectrum-scale-snapshot-2
spec:
  volumeSnapshotClassName: ibm-spectrum-scale-snapshotclass-advance
  source:
    persistentVolumeClaimName: scale-advance-pvc-1
[ocp ]# oc apply -f snapshot1.yaml
volumesnapshot.snapshot.storage.k8s.io/ibm-spectrum-scale-snapshot-2 created
[ocp ]# oc get vs
NAME                            READYTOUSE   SOURCEPVC             SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS                              SNAPSHOTCONTENT                                    CREATIONTIME   AGE
ibm-spectrum-scale-snapshot-1   true         scale-advance-pvc-1                           1Gi           ibm-spectrum-scale-snapshotclass-advance   snapcontent-852bbcb2-ce98-408b-8346-4bfa04c64cb7   2m16s          2m33s
ibm-spectrum-scale-snapshot-2   true         scale-advance-pvc-1                           1Gi           ibm-spectrum-scale-snapshotclass-advance   snapcontent-1e419d4a-3411-4d6f-97d4-8991eb0c179c   2m16s          50s
```
5. Delete the snapshot created :
```
[ocp ]# oc delete vs ibm-spectrum-scale-snapshot-1
volumesnapshot.snapshot.storage.k8s.io "ibm-spectrum-scale-snapshot-1" deleted
```
6. Check the logs 
```
I0104 11:16:50.218761       1 controllerserver.go:2638] [3019c5c7-0db0-426c-83d9-6439d380251b] DelSnapMetadataDir - number of links for directory in FS [fs0] at path [76f46cc4-7189-4efc-bd90-536c82255aea-ibm-spectrum-scale-csi/snapshot-852bbcb2-ce98-408b-8346-4bfa04c64cb7] is [3]
E0104 11:16:50.218801       1 controllerserver.go:2744] [3019c5c7-0db0-426c-83d9-6439d380251b] DeleteSnapshot - error while deleting snapshot snapshot-852bbcb2-ce98-408b-8346-4bfa04c64cb7: Error: rpc error: code = Internal desc = unable to delete directory for FS [fs0] at path [76f46cc4-7189-4efc-bd90-536c82255aea-ibm-spectrum-scale-csi/snapshot-852bbcb2-ce98-408b-8346-4bfa04c64cb7] as there is reference. Error: [<nil>]
E0104 11:16:50.218843       1 utils.go:69] [3019c5c7-0db0-426c-83d9-6439d380251b] GRPC error: rpc error: code = Internal desc = unable to delete directory for FS [fs0] at path [76f46cc4-7189-4efc-bd90-536c82255aea-ibm-spectrum-scale-csi/snapshot-852bbcb2-ce98-408b-8346-4bfa04c64cb7] as there is reference. Error: [<nil>]
```

observation : metasnapdir is getting deleted from scale side but from k8s side above error log is coming 

## Expected behavior
Volume snapshot should be deleted

## logs :
/scale-csi/D.1082
csisnap.tar.gz
