### ISSUE TITLE
Incorrect  SCC

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#112]
**Describe the bug**
Had an issue with a Cloud Pak Service that got stuck being assigned to the csiaccess SCC for some reason.  It seems like this Group should not be included in the SCC and only the Users (SAs used by Scale).  
```
oc describe scc csiaccess  
Name:						csiaccess
Priority:					<none>
Access:						
 Users:					system:serviceaccount:spectrum-scale:ibm-spectrum-scale-csi-attacher,system:serviceaccount:spectrum-scale:ibm-spectrum-scale-csi-provisioner,system:serviceaccount:spectrum-scale:ibm-spectrum-scale-csi-node
 Groups:					system:authenticated
```

**Comment by mew2057** [comment]
At the time of this bu  this  was the  scc config file:
```
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  annotations:
    kubernetes.io/description: allow hostpath and host network to be accessible
  generation: 1
  name: csiaccess
  selfLink: /apis/security.openshift.io/v1/securitycontextconstraints/csiaccess
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- persistentVolumeClaim
- projected
- secret
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: []
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups:
- system:authenticated
{% if csiaccess_users|length > 0 %}
users:
{% for user in csiaccess_users %}
  - "{{user}}"
{% endfor %}
{% endif %}
```
