### ISSUE TITLE
readonly cache volume PVC doesn't get created 

### ISSUE THREAD

**Issue by saurabhwani5** [IBM/ibm-spectrum-scale-csi#1218]
## Describe the bug
readonly cache volume PVC does not get created with log error as `Internal desc = unable to create directory [pvc-0824b148-4f89-4a91-b9af-8c5eb9f7dd25/.cachevolumetmp] in filesystem [fs0]. Error : [EFSSG0763C The parent directory "/var/gpfs/fs0/pvc-0824b148-4f89-4a91-b9af-8c5eb9f7dd25/.cachevolumetmp" of the specified junction path does not exist.]`

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. Create Secret as following :
```
oc create secret generic cache-s3-pvc1-secret \
--from-literal=endpoint=<endpoint> --from-literal=bucket=<bucketname> \
--from-literal=accesskey=<accesskey> --from-literal=secretkey=<secretkey>
```
2. Create Storage Class :
```
[root@ocp yaml]# cat sc.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ibm-scale-cache-s3
provisioner: spectrumscale.csi.ibm.com
parameters:
  volBackendFs: "fs0"
  volumeType: "cache"
  cacheMode: "readonly"
  csi.storage.k8s.io/provisioner-secret-name: ${pvc.name}-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  # AFM params can also be specified here (not for MVP)
reclaimPolicy: Delete
allowVolumeExpansion: true
```

3. Create PVC :
```
[root@ocp yaml]# cat pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache-s3-pvc1
spec:
  storageClassName: ibm-scale-cache-s3
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
```
      
4. Check PVC description :
```
[root@ocp yaml]# oc describe pvc
Name:          cache-s3-pvc1
Namespace:     ibm-spectrum-scale-csi
StorageClass:  ibm-scale-cache-s3
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: spectrumscale.csi.ibm.com
               volume.kubernetes.io/storage-provisioner: spectrumscale.csi.ibm.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                   From                                                                                                                Message
  ----     ------                ----                  ----                                                                                                                -------
  Normal   ExternalProvisioning  3m42s (x43 over 13m)  persistentvolume-controller                                                                                         Waiting for a volume to be created either by the external provisioner 'spectrumscale.csi.ibm.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  Normal   Provisioning          50s (x10 over 13m)    spectrumscale.csi.ibm.com_ibm-spectrum-scale-csi-provisioner-7f698474dd-tbqq8_0531fe5f-53d3-4318-b592-f513472acb9e  External provisioner is provisioning volume for claim "ibm-spectrum-scale-csi/cache-s3-pvc1"
  Warning  ProvisioningFailed    18s (x10 over 12m)    spectrumscale.csi.ibm.com_ibm-spectrum-scale-csi-provisioner-7f698474dd-tbqq8_0531fe5f-53d3-4318-b592-f513472acb9e  failed to provision volume with StorageClass "ibm-scale-cache-s3": rpc error: code = Internal desc = unable to create directory [pvc-0824b148-4f89-4a91-b9af-8c5eb9f7dd25/.cachevolumetmp] in filesystem [fs0]. Error : [EFSSG0763C The parent directory "/var/gpfs/fs0/pvc-0824b148-4f89-4a91-b9af-8c5eb9f7dd25/.cachevolumetmp" of the specified junction path does not exist.]
[root@ocp yaml]#
```

## Expected behavior
Readonly cache volume PVC should be created 

### Data Collection and Debugging
```
/scale-csi/D.1218
mustgather.tar.gz
```
