### ISSUE TITLE
ReadOnlyMany does not work with static provisioning

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#122]
As a system admin I created the following static pv:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-images
  labels:
    id: images
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  csi:
    driver: ibm-spectrum-scale-csi
    volumeHandle: 17399599334479190260;099B6A42:5DC52700;path=/mnt/remote_fs0_1m/static/images
```

Unfortunately, a user can still write to the PV if he mounts the volume. This should not be allowed. 

Please fix it as it affects my AI workloads.
