### ISSUE TITLE
Make the changes for driver name in static provisioning pv example 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#133]
**Describe the bug**
Make the changes for driver name in static provisioning pv example 

**To Reproduce**

Make the changes for driver name to spectrumscale.csi.ibm.com in static provisioning pv example here :
https://github.com/IBM/ibm-spectrum-scale-csi/blob/v1.1.0/driver/examples/static/static_pv.yaml

```
apiVersion: v1
kind: PersistentVolume
metadata:
        name: static-scale-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: ibm-spectrum-scale-csi
    volumeHandle: "clusterID;FSUID;path=/gpfs/fs1/staticdir"
```

**Expected behavior**
Make the changes for driver name to spectrumscale.csi.ibm.com in static provisioning pv example 

**Environment**
Please run the following an paste your output here:

**Additional context**
