### ISSUE TITLE
Make clusterID optional for Storage classes of Fileset Dynamic provisioning

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#16]
As for now, if you create a storage class for dynamic provisioning of gpfs filesets, you need to provide a cluster id. This is redundant. The filesystem name only should be sufficient as the names are unique in a gpfs cluster. Please make the cluster ID optional for storage classes. Sample storage class:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-fileset
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "gpfs0"
    clusterId: "17399599334479190260"  <--- MAKE IT OPTIONAL
reclaimPolicy: Delete
```
