### ISSUE TITLE
Create secrets automatically when deploying driver instances

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#171]
Currently, I need to create secrets before I start creating a CSI driver instance. Could you add to the `spec` section of the yaml file fields for username and password? What I would like to see would look as follows:

NOW:
```
spec:
  clusters:
    - id: '17399599334479190260'
      primary:
        primaryFs: remote_fs0_1m
        primaryFset: test
        remoteCluster: "4473793006880872527"
        remoteFs: fs0_1m
      restApi:
        - guiHost: 10.10.1.21
      secrets: csisecret-local <-- I NEED TO CREATE IT MANUALLY BEFORE
      secureSslMode: false
  scaleHostpath: /mnt/remote_fs0_1m
```

MY PROPOSAL:
```
spec:
  clusters:
    - id: '17399599334479190260'
      primary:
        primaryFs: remote_fs0_1m
        primaryFset: test
        remoteCluster: "4473793006880872527"
        remoteFs: fs0_1m
      restApi:
        - guiHost: 10.10.1.21
      username: csiuser   <-- AUTOMATICALLY CREATES A SECRET FROM USERNAME AND PASSWORD
      password: mypassword  <-- PASSWORD FIELD
      secureSslMode: false
  scaleHostpath: /mnt/remote_fs0_1m
```
With the change, a setup would become easier.
