### ISSUE TITLE
Describe how to use remote fs as primary fs only

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#19]
In the configuration yaml you describe how to use a remote filesystem. I would need to use one as my primary fs, I dont want use any local filesystems. How should the configuration look like ? Should the primary cluster ID be my remote ID ? Do I need to specify credentials for my local GUI as I only intend to use my remote filesystems ? Or only for the remote GUI?

```
  clusters:
    - id: "< Primary Cluster ID - WARNING: THIS IS A STRING NEEDS YAML QUOTES!>"
      secrets: "secret1"
      secureSslMode: false
      primary:
        primaryFs: "< Primary Filesystem >"
        primaryFset: "< Fileset in Primary Filesystem >"
#        inodeLimit: "< node limit for Primary Fileset >" # Optional
#        remoteCluster: "< Remote ClusterID >"            # Optional - This ID should have seperate entry in Clusters map.
#        remoteFs: "< Remote Filesystem >"                # Optional
#      cacert: "< CA cert configmap for GUI >"            # Optional
      restApi: 
      - guiHost: "< Primary cluster GUI IP/Hostname >" 
```
Can you provide a basic sample for a single remote fs only?

**Comment by smitaraut** [comment]
Documentation is available in KC at-
https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_config_csi_remotemount_final.html

**Comment by deeghuge** [comment]
@przem123 , based on your requirement, configuration will look like something as shown below

```
  clusters:
    - id: "<Cluster ID of Local Cluster>"
      secrets: "secret1"        # secret containing username/password of local GUI server
      secureSslMode: false
      primary:
        primaryFs: "remote_fs0_1m"
        primaryFset: "< Fileset name>"
        remoteCluster: "< Cluster ID of Remote Cluster >"         
        remoteFs: "fs0_1m"                
      restApi: 
      - guiHost: "<Local cluster GUI ip >" 

    - id: "<Cluster ID of Remote Cluster>"
      secrets: "secret2"        # secret containing username/password of remote GUI server
      secureSslMode: false    
      restApi: 
      - guiHost: "<Remote cluster GUI ip >" 
```
