### ISSUE TITLE
csi-node-driver-registrar should create plugin dir with new spectrumscale driver name 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#199]
**Describe the bug**
csi-node-driver-registrar should create plugin dir with new spectrumscale driver name 

see example : https://github.com/kubernetes-csi/node-driver-registrar#example

**To Reproduce**
```
  containers:
  - args:
    - --v=5
    - --csi-address=$(ADDRESS)
    - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
    env:
    - name: ADDRESS
      value: /var/lib/kubelet/plugins/ibm-spectrum-scale-csi/csi.sock
    - name: CHECKSUM
      value: bc75f1cfda75a8d416490c17a42bd80dc03f2da4
    - name: DRIVER_REG_SOCK_PATH
      value: /var/lib/kubelet/plugins/ibm-spectrum-scale-csi/csi.sock
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
    imagePullPolicy: IfNotPresent
    name: driver-registrar
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/kubelet/plugins/ibm-spectrum-scale-csi
      name: plugin-dir
```

**Expected behavior**
csi-node-driver-registrar should create plugin dir with new spectrumscale driver name
