### ISSUE TITLE
delete snapshot command hangs if that snapshot was created using dependent fileset / lightweight directory PVC.

### ISSUE THREAD

**Issue by kulkarnicr** [IBM/ibm-spectrum-scale-csi#267]
**Describe the bug**
delete snapshot command hangs if that snapshot was created using dependent fileset / lightweight directory PVC.

Please note, this is different from issue #251 where delete snapshot succeeds, but delete PVC hangs.
Whereas, in this issue, I'm observing delete snapshot itself hangs.

**To Reproduce**
test builds
```
    Image:         quay.io/smitaraut/ibm-spectrum-scale-csi-operator:snap0727
    Image:         quay.io/smitaraut/ibm-spectrum-scale-csi-driver:snap0727
    Image:         quay.io/k8scsi/snapshot-controller:canary
    Image:         quay.io/k8scsi/csi-snapshotter:canary
```

1. create dependent fileset PVC
```
[root@gn1 2020_07_27-07:05:55 RTC252477]$ knsc
NAME         PROVISIONER                 RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
sc-depfset   spectrumscale.csi.ibm.com   Delete          Immediate           false                  4s
sc-lwdir     spectrumscale.csi.ibm.com   Delete          Immediate           false                  64s
[root@gn1 2020_07_27-07:05:58 RTC252477]$
[root@gn1 2020_07_27-07:06:21 RTC252477]$ knpvc
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-depfset   Bound    pvc-b8791de6-a130-4cff-977e-93a6d690fcdd   1Gi        RWX            sc-depfset     21s
pvc-lwdir     Bound    pvc-9d3f6055-59ff-454b-808d-37f250a99431   1Gi        RWX            sc-lwdir       76s
[root@gn1 2020_07_27-07:06:25 RTC252477]$
```

2. create volumesnapshot from dependent fileset (it remains in readytouse=false as expected)

```
[root@gn1 2020_07_27-07:06:39 RTC252477]$ knvs
NAME         READYTOUSE   SOURCEPVC     SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT                                    CREATIONTIME   AGE
vs-depfset   false        pvc-depfset                                         vsclass1        snapcontent-f576db5b-3237-4be5-a3bf-db8fc5139653                  1s
vs-lwdir     false        pvc-lwdir                                           vsclass1        snapcontent-bedc290f-58c4-4e62-8b46-7235eee8a60c                  64s
[root@gn1 2020_07_27-07:06:40 RTC252477]$
```

3. try deleting above snapshot (command hangs)

```
[root@gn1 2020_07_27-07:14:53 RTC252477]$ kubectl -n ibm-spectrum-scale-csi-driver delete volumesnapshot vs-lwdir
volumesnapshot.snapshot.storage.k8s.io "vs-lwdir" deleted
^C
[root@gn1 2020_07_27-07:15:33 RTC252477]$ kubectl -n ibm-spectrum-scale-csi-driver describe volumesnapshot vs-lwdir
[root@gn1 2020_07_27-08:21:55 RTC252477]$ kubectl -n ibm-spectrum-scale-csi-driver delete volumesnapshot vs-depfset
volumesnapshot.snapshot.storage.k8s.io "vs-depfset" deleted
^C
[root@gn1 2020_07_27-08:22:07 RTC252477]$
```

**Expected behavior**
snapshot delete command should succeed.

**Environment**
Please run the following an paste your output here:
``` bash
# Developement
operator-sdk version 
go version

# Deployment
kubectl version
rpm -qa | grep gpfs

[root@gn1 2020_07_27-08:23:23 RTC252477]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
[root@gn1 2020_07_27-08:23:25 RTC252477]$
[root@gn4 2020_07_27-08:24:45 ~]$ mmdiag --version

=== mmdiag: version ===
Current GPFS build: "5.0.5.1 ".
Built on Jul  9 2020 at 14:02:23
Running 11 days 5 hours 17 minutes 29 secs, pid 18180
[root@gn4 2020_07_27-08:24:51 ~]$
[root@gn4 2020_07_27-08:24:51 ~]$ rpm -qa | grep gui
gpfs.gui-5.0.5-2.noarch
[root@gn4 2020_07_27-08:24:55 ~]$
```
**Screenshots**

**Additional context**
yaml files that I used to create storageclass, PVC, volumesnapshot.

```
[root@gn1 2020_07_27-08:59:58 RTC252477]$ cat sc_depfset.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: sc-depfset
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "fs2"
    clusterId: "17630041144725828029"
    filesetType: "dependent"
    parentFileset: "fset1"
reclaimPolicy: Delete
[root@gn1 2020_07_27-09:00:01 RTC252477]$
[root@gn1 2020_07_27-09:00:02 RTC252477]$ cat pvc_depfset.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-depfset
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-depfset

[root@gn1 2020_07_27-09:00:06 RTC252477]$
[root@gn1 2020_07_27-09:00:07 RTC252477]$ cat vs_depfset.yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: vs-depfset
spec:
  volumeSnapshotClassName: vsclass1
  source:
    persistentVolumeClaimName: pvc-depfset
[root@gn1 2020_07_27-09:00:10 RTC252477]$
```
