### ISSUE TITLE
 The sum of the max inodes for all independent file sets may not exceed the maximum possible inodes for scale0 capacity

### ISSUE THREAD

**Issue by YiannisGkoufas** [IBM/ibm-spectrum-scale-csi#295]
**Describe the bug**
Error when creating a pvc

**To Reproduce**
Create a storageclass as follows:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-fileset
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: scale0
    clusterId: "10588301405191899994"
    inodeLimit: "1024"
reclaimPolicy: Delete
```
Create a pvc as follows:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scale-fset-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100m
  storageClassName: ibm-spectrum-scale-csi-fileset
```
Getting the error:
```
  Warning  ProvisioningFailed    0s               spectrumscale.csi.ibm.com_ibm-spectrum-scale-csi-provisioner-0_c5ba8032-1e0b-4703-8cfd-ec3ad300e6fb  failed to provision volume with StorageClass "ibm-spectrum-scale-csi-fileset": rpc error: code = Internal desc = Unable to create fileset [pvc-4b32eff0-8edf-4f11-8db6-617ebb96c098] in FS [scale0]. Error [[EFSSG0740C There are not enough resources available to create a new independent file set. The sum of the max inodes for all independent file sets may not exceed the maximum possible inodes for scale0 capacity. EFSSG0740C There are not enough resources available to create a new independent file set. The sum of the max inodes for all independent file sets may not exceed the maximum possible inodes for scale0 capacity.]]
```

**Expected behavior**
To obtain the needed PVC

Probably there is a gpfs configuration needed that I missed.
