### ISSUE TITLE
Deploy Operator via CLI and OC

### ISSUE THREAD

**Issue by Issen007** [IBM/ibm-spectrum-scale-csi#301]
**Describe the bug**
I can only deploy IBM Spectrum Scale CSI Operator via Openshift GUI and not via oc

**To Reproduce**
1. Try to deploy the Operator via oc and it will stop after deploy and not continue as it does with the GUI.

**Expected behavior**
I expect it should deploy the operator in the same way as the GUI does or a propare documentation on this. 

**Environment**
Please run the following an paste your output here:
``` 
Client Version: 4.3.13
Server Version: 4.5.4
Kubernetes Version: v1.18.3+012b3ec
```
**Screenshots**

**Additional context**

**Comment by smitaraut** [comment]
What steps are you following to deploy the operator via CLI? Can you give details of the error message you are seeing, either in command output or in pod logs?

**Comment by Issen007** [comment]
My understanding is that I only need to deploy following yaml file.
```
apiVersion: v1
kind: Namespace
metadata:
  name: ibm-spectrum-scale-csi-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: ibm-spectrum-scale-csi-operator
spec:
  targetNamespaces:
  - ibm-spectrum-scale-csi-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-spectrum-scale-csi-operator
  namespace: ibm-spectrum-scale-csi-operator
spec:
  channel: stable
  name: ibm-spectrum-scale-csi-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
```
But this is not working.  And I guess it's more steps but their is no documentation that showing anything else then GUI version.
