### ISSUE TITLE
Custom Resource creation fails on ppc64le with imagepullsecret option 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#303]
**Describe the bug**
Custom Resource creation fails on ppc64le with imagepullsecret option 

**To Reproduce**
1. Custom Resource creation fails on ppc64le with imagepullsecret option 

Custom resource file snippet 
```
---
apiVersion: csi.ibm.com/v1
kind: "CSIScaleOperator"
metadata:
  name: "ibm-spectrum-scale-csi"
  namespace: "ibm-spectrum-scale-csi-driver"
  labels:
    app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    release: ibm-spectrum-scale-csi-operator
status: {}
spec:
# The path to the GPFS file system mounted (either remote/local) on the local Spectrum Scale API host machine.
# ==================================================================================
  scaleHostpath: "/ibm/gpfs0"

# A passthrough option that distributes an imagePullSecrets array to the containers
# generated by the csi scale operator. Please refer to official k8s documentation for
# your environment for more details. https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# ==================================================================================
  imagePullSecrets:
    - 8066833-jainbrtibm-pull-secret

# Below specifies the details of a SpectrumScale cluster configuration used by the
# plugin. It can have multiple values.
# ==================================================================================
  clusters:
    - id: "2854885507942369942"
      secrets: "secret1"
      secureSslMode: false
      primary:
        primaryFs: "gpfs0"
```
create CR object failed with below validation error
```
[root@powerup1 ]# kubectl apply -f ../../operator/deploy/crds/csiscaleoperators.csi.ibm.com_cr.yaml
error: error validating "../../operator/deploy/crds/csiscaleoperators.csi.ibm.com_cr.yaml": error validating data: ValidationError(CSIScaleOperator.spec): unknown field "imagePullSecrets" in com.ibm.csi.v1.CSIScaleOperator.spec; if you choose to ignore these errors, turn validation off with --validate=false


```
**Expected behavior**
Custom Resource should be created 

**Environment**
```
[root@powerup1 ]# kubectl get nodes
NAME                    STATUS   ROLES    AGE   VERSION
powerup1.fyre.ibm.com   Ready    master   26h   v1.19.0
powerup2.fyre.ibm.com   Ready    worker   26h   v1.19.0
powerup3.fyre.ibm.com   Ready    worker   26h   v1.19.0


[root@powerup1 ]# docker info
Containers: 18
 Running: 16
 Paused: 0
 Stopped: 2
Images: 8
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-1127.18.2.el7.ppc64le
Operating System: Red Hat Enterprise Linux Server 7.8 (Maipo)
OSType: linux
Architecture: ppc64le
CPUs: 4
Total Memory: 7.473GiB
Name: powerup1.fyre.ibm.com
ID: QM6U:XTO4:FD3K:CLTV:EV73:KEHX:ZO6C:6B7T:C3LG:DCR6:MTYC:5JEP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


[root@powerup1 ]# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/ppc64le"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/ppc64le"}


[root@powerup1 ]# /usr/lpp/mmfs/bin/mmdiag
Current GPFS build: "5.1.0.0 200902.111319".
Built on Sep  2 2020 at 11:23:11
Running 22 hours 55 minutes 14 secs, pid 7641

Run mmdiag --help for more options

[root@powerup1 ]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)
```
