### ISSUE TITLE
Changing setting in cr.yaml file from ssl to non-ssl, is not reflecting on deamonset's pods

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#323]
**Describe the bug**
Changing setting in cr.yaml file from ssl to non-ssl, is not reflecting on deamonset's pods 

**To Reproduce**
1. Applied operator and cr.yaml file as below 

Snippet of the cr.yaml file 

```
  clusters:
    - id: "6544305008369427178"
      secrets: "guisecretlocal"
      secureSslMode: true
      primary:
        primaryFs: "gpfs0"
        inodeLimit: "1024" # Optional
#        remoteCluster: "5671145063406913128"            # Optional - This ID should have seperate entry in Clusters map.
      cacert: "localconf1"              # Optional
      restApi:
        - guiHost: "oc-w6.ocp.openshift.scale.net"
#
# In the case we have multiple clusters, specify their configuration below.
# ==================================================================================
    - id: "5671145063406913128"
      secrets: "guisecretremote"
      secureSslMode: false
#      cacert: "remoteconf1"
      restApi:
      - guiHost: "remote-w1.ocp.openshift.scale.net"

```
2. Pods are in ContainerCreating state as expected because configmap was not created/present 

```
[root@oc-w3 configfile]# oc apply -f  csiscaleoperators.csi.ibm.com_cr_test.yaml
csiscaleoperator.csi.ibm.com/ibm-spectrum-scale-csi configured



[root@oc-w3 configfile]# oc get pods -w
NAME                                               READY   STATUS              RESTARTS   AGE
ibm-spectrum-scale-csi-attacher-0                  1/1     Running             0          9m56s
ibm-spectrum-scale-csi-gtntz                       0/2     ContainerCreating   0          9m46s
ibm-spectrum-scale-csi-j4k65                       0/2     ContainerCreating   0          9m46s
ibm-spectrum-scale-csi-operator-675c6f78c9-rxgx5   1/1     Running             0          3d18h
ibm-spectrum-scale-csi-provisioner-0               1/1     Running             0          9m51s


[root@oc-w3 configfile]# oc describe pod ibm-spectrum-scale-csi-gtntz  
.
.
Events:
  Type     Reason       Age                   From                                    Message
  ----     ------       ----                  ----                                    -------
  Normal   Scheduled    6m24s                 default-scheduler                       Successfully assigned ibm-spectrum-scale-csi-driver/ibm-spectrum-scale-csi-gtntz to oc-w4.ocp.openshift.scale.net
  Warning  FailedMount  4m21s                 kubelet, oc-w4.ocp.openshift.scale.net  Unable to attach or mount volumes: unmounted volumes=[localconf1], unattached volumes=[registration-dir ibm-spectrum-scale-csi-node-token-g88rp spectrum-scale-config gpfs-classic plugin-dir guisecretremote localconf1 pods-mount-dir guisecretlocal host-dev]: timed out waiting for the condition
  Warning  FailedMount  2m5s                  kubelet, oc-w4.ocp.openshift.scale.net  Unable to attach or mount volumes: unmounted volumes=[localconf1], unattached volumes=[registration-dir gpfs-classic guisecretlocal localconf1 host-dev spectrum-scale-config pods-mount-dir guisecretremote plugin-dir ibm-spectrum-scale-csi-node-token-g88rp]: timed out waiting for the condition
  Warning  FailedMount  12s (x11 over 6m24s)  kubelet, oc-w4.ocp.openshift.scale.net  MountVolume.SetUp failed for volume "localconf1" : configmap "localconf1" not found
```

3. Now ssl mode is set to false and cacert line is commented and reapplied the cr.yaml file again 

Snippet of the cr.yaml file 

```
  clusters:
    - id: "6544305008369427178"
      secrets: "guisecretlocal"
      secureSslMode: false
      primary:
        primaryFs: "gpfs0"
        inodeLimit: "1024" # Optional
#        remoteCluster: "5671145063406913128"            # Optional - This ID should have seperate entry in Clusters map.
#      cacert: "localconf1"              # Optional
      restApi:
        - guiHost: "oc-w6.ocp.openshift.scale.net"
#
# In the case we have multiple clusters, specify their configuration below.
# ==================================================================================
    - id: "5671145063406913128"
      secrets: "guisecretremote"
      secureSslMode: false
#      cacert: "remoteconf1"
      restApi:
      - guiHost: "remote-w1.ocp.openshift.scale.net"

```
```
[root@oc-w3 configfile]# oc apply -f  csiscaleoperators.csi.ibm.com_cr_test.yaml
csiscaleoperator.csi.ibm.com/ibm-spectrum-scale-csi configured
```

Deamonset's pod restarted but failed saying "configmap "localconf1" not found"

```
[root@oc-w3 configfile]# oc get pods
NAME                                               READY   STATUS              RESTARTS   AGE
ibm-spectrum-scale-csi-6mfjj                       0/2     ContainerCreating   0          64s
ibm-spectrum-scale-csi-attacher-0                  1/1     Running             0          27m
ibm-spectrum-scale-csi-operator-675c6f78c9-rxgx5   1/1     Running             0          3d18h
ibm-spectrum-scale-csi-provisioner-0               1/1     Running             0          26m
ibm-spectrum-scale-csi-zdvwb                       0/2     ContainerCreating   0          67s
```
```

[root@oc-w3 configfile]# oc describe pod ibm-spectrum-scale-csi-6mfjj
.
.
Events:
  Type     Reason       Age                From                                    Message
  ----     ------       ----               ----                                    -------
  Normal   Scheduled    45s                default-scheduler                       Successfully assigned ibm-spectrum-scale-csi-driver/ibm-spectrum-scale-csi-6mfjj to oc-w5.ocp.openshift.scale.net
  Warning  FailedMount  14s (x7 over 45s)  kubelet, oc-w5.ocp.openshift.scale.net  MountVolume.SetUp failed for volume "localconf1" : configmap "localconf1" not found
```

**Expected behavior**
Changing setting in cr.yaml file from ssl to non-ssl, should restart deamonset's pod without configmap in pod's configuration 

**Environment**
Please run the following an paste your output here:
OCP 4.5.8
