### ISSUE TITLE
operator namespace and driver should be allowed to be separate namespaces  

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#38]
**Describe the bug**
operator namespace and driver should be allowed to be separate namespaces  

**To Reproduce**
1. Create the operator under namepsace = ibm-spectrum-scale-csi-driver

```
[root@oc-w3 ibm-spectrum-scale-csi-operator]# oc get all
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/ibm-spectrum-scale-csi-operator-6d4bd865f6-bn7zf   2/2     Running   0          13s

NAME                                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/ibm-spectrum-scale-csi-operator-metrics   ClusterIP   172.30.233.186   <none>        8383/TCP   4s

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ibm-spectrum-scale-csi-operator   1/1     1            1           13s

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/ibm-spectrum-scale-csi-operator-6d4bd865f6   1         1         1       13s
```

2. Create the secret and configmap for GUI certificate in namespace=default 

```
[root@oc-w3 ibm-spectrum-scale-csi-operator]# oc get secrets guisecret -n default
NAME        TYPE     DATA   AGE
guisecret   Opaque   2      3h15m
[root@oc-w3 ibm-spectrum-scale-csi-operator]# oc get configmap -n default
NAME             DATA   AGE
guicertificate   1      3h17m
```

3. make the changes in deploy/crds/ibm-spectrum-scale-csi-operator-cr.yaml file
```
apiVersion: csi.ibm.com/v1
kind: 'CSIScaleOperator'
metadata:
    name: 'ibm-spectrum-scale-csi'
    namespace: 'default'
    labels:
      app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
      app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
      app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    release: ibm-spectrum-scale-csi-operator

```
4. Starting the CSI Driver

```
[root@oc-w3 ibm-spectrum-scale-csi-operator]# oc apply -f  deploy/crds/ibm-spectrum-scale-csi-operator-cr.yaml
csiscaleoperator.csi.ibm.com/ibm-spectrum-scale-csi created

[root@oc-w3 ibm-spectrum-scale-csi-operator]# oc get CSIScaleOperator -n default
NAME                     AGE
ibm-spectrum-scale-csi   58s


[root@oc-w3 ibm-spectrum-scale-csi-operator]# oc get pods -n default
No resources found.

```

**Expected behavior**
 ibm-spectrum-scale-csi-driver namespace for operator and another namespace for driver should work 

**Environment**
Please run the following an paste your output here:

```
[root@oc-w3 ibm-spectrum-scale-csi-operator]# oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.2.0     True        False         46d     Cluster version is 4.2.0

```

**Screenshots**

**Additional context**
