### ISSUE TITLE
Full support of subPath option for storage class with non-root uid/gid

### ISSUE THREAD

**Issue by gfschmidt** [IBM/ibm-spectrum-scale-csi#424]
**Is your feature request related to a problem? Please describe.**
The _IBM Watson Machine Learning Accelerator_ (WMLA) component for _IBM Cloud Pak for Data_ (CP4D) seems to make excessive use of `subPath` to mount all the specified the sub-directories of the PV holding the user's data individually to selected mount points in the pod as follows: 
```
    volumeMounts:
    - mountPath: /gpfs/mygpfs
      name: mygpfs
      subPath: mygpfs
    - mountPath: /gpfs/myresultfs
      name: mygpfs
      subPath: myresultfs
    - mountPath: /gpfs/mydatafs
      name: mygpfs
      subPath: mydatafs
    - mountPath: /gpfs/dlim
      name: mygpfs
      subPath: dlim
```
instead of mounting the whole PV to a _single_ mount point in the pod with all its sub-directories:
```
    volumeMounts:
    - mountPath: /gpfs/mygpfs
      name: mygpfs
```
The WMLA service of CP4D uses this concept to dynamically map the users' Jupyter notebook data into the pods using subPaths.

With CSI v2.1.0 it seems when using `subPath` it does not apply the correct uid/gid settings from the storage class so a non-root user loses access to these directories in the pod.  

From within the pod it looks as follows:
```
sh-4.2$ ls -al
total 25
drwxr-xr-x.   1 root       root          70 May  6 14:48 .
drwxr-xr-x.   1 root       root          70 May  6 14:48 ..
[...]
drwxr-xr-x.   6 root       root          66 Jan 21 01:05 gpfs            <<< subPath mounts without proper uid/gid
[...]
drwxrwx--x.   4 1000750000 1000750000  4096 May  6 03:32 wmla-logging        <<< regular mount with proper uid/gid
```
with
```
sh-4.2$ ls -al /gpfs/
total 2
drwxr-xr-x. 6 root       root   66 Jan 21 01:05 .
drwxr-xr-x. 1 root       root   70 May  6 14:48 ..
drwxrwx--x. 2 root       root 4096 May  6 03:31 dlim
drwxrwx--x. 2 root       root 4096 May  6 14:45 mydatafs
drwxrwx--x. 3 root       root 4096 May  6 15:19 mygpfs
drwxrwx--x. 7 root       root 4096 May  6 15:04 myresultfs
```
The directory in IBM Spectrum Scale backing the PVC (here light-weight provisioned from a storage class with uid: "1000750000" and gid: "1000750000") is:
```
# ls -al /gpfs/ess3000_1M/wmla/pvc-9c13e6ab-29c7-4e78-a360-0df6a0290749
total 3
drwxrwx--x.  6 1000750000 1000750000 4096 May  6 05:31 .
drwxrwxrwx. 15 root       root       4096 May  6 05:34 ..
drwxrwx--x.  2 root       root       4096 May  6 05:31 dlim
drwxrwx--x.  2 root       root       4096 May  6 05:31 mydatafs
drwxrwx--x.  2 root       root       4096 May  6 05:31 mygpfs
drwxrwx--x.  4 root       root       4096 May  6 05:34 myresultfs
```
and the uid/gid settings are not properly applied as specified the storage class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-wmla-sc
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "fs1"
    volDirBasePath: "wmla"
    uid: "1000750000"
    gid: "1000750000"
reclaimPolicy: Delete
```
Furthermore, these individual "mounts" via `subPath` also do NOT appear in the `df -h` output from within the pod at all:
```
sh-4.2$ df -h
Filesystem                            Size  Used Avail Use% Mounted on
overlay                               446G   42G  404G  10% /
tmpfs                                  64M     0   64M   0% /dev
tmpfs                                  63G     0   63G   0% /sys/fs/cgroup
tmpfs                                  63G     0   63G   0% /dev/shm
tmpfs                                  63G   16M   63G   1% /etc/passwd
fs1                                    15T 1017G   14T   7% /wmla-logging        <<< this is another Scale PVC mounted at /wmla-logging (no subPath used)
tmpfs                                  63G   12K   63G   1% /etc/etcd
/dev/mapper/coreos-luks-root-nocrypt  446G   42G  404G  10% /etc/hosts
tmpfs                                  63G  4.0K   63G   1% /var/tmp/conf
tmpfs                                  63G   28K   63G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                  63G     0   63G   0% /proc/acpi
tmpfs                                  63G     0   63G   0% /proc/scsi
tmpfs                                  63G     0   63G   0% /sys/firmware
```
Another Scale PVC (wmla-logging) NOT using the `subPath` option appears in the `df -h` output as expected and also carries all the uid/gid settings from the storage class correctly:
```
sh-4.2$ ls -alR /wmla-logging/
/wmla-logging/:
total 2
drwxrwx--x. 4 1000750000 1000750000 4096 May  6 03:32 .
drwxr-xr-x. 1 root       root         70 May  6 03:31 ..
drwxr-xr-x. 2 1000750000 1000750000 4096 May  6 03:32 dli
drwxr-xr-x. 2 1000750000 1000750000 4096 May  6 03:32 notebook
```
It looks like the `subPath` option is not fully supported with CSI v2.1.0 yet as the uid/gid settings from the storage class do not seem to be applied properly, especially when using `subPath` with non-root user and group id.
 
**Describe the solution you'd like**
Full support of the `subPath` option with CSI also applying the correct uid/gid settings as specified in the storage class for non-root uid/gid.
