### ISSUE TITLE
SELinux prevents access to existing sub-directories in statically provisioned PVs

### ISSUE THREAD

**Issue by gfschmidt** [IBM/ibm-spectrum-scale-csi#481]
**Describe the bug**

When using *static provisioning* in OpenShift 4.7 with Scale CSI v2.2.0 to gain access to an entire IBM Spectrum Scale file system (e.g. mounted at /mnt/fs1 in CNSA) with existing data then *SELinux on the worker node prevents access to existing sub-directories* even when running the pod under OpenShift with *cluster-admin* role. This was observed with IBM Spectrum Scale CNSA v5.1.1.1 and CSI v2.2.0 on x86 and OpenShift 4.7.17.

**To Reproduce**

0. We have an existing file system in IBM Spectrum Scale that we want to make available in OpenShift with static provisioning:

File system attributes on CNSA:
```
sh-4.4# mmlscluster
GPFS cluster information
========================
  GPFS cluster name:         ibm-spectrum-scale.ibm-spectrum-scale.ocp4.scale.ibm.com
  GPFS cluster id:           17399599334533218545

sh-4.4# mmlsfs fs1 --uid
flag                value                    description
------------------- ------------------------ -----------------------------------
 --uid              099B6A7A:5EB99721        File system UID

sh-4.4# mmremotefs show     
Local Name  Remote Name  Cluster name       Mount Point        Mount Options    Automount  Drive  Priority
fs1         ess3000_1M   ess3000.bda.scale.ibm.com /mnt/fs1           rw               yes          -        0
```
File system attributes on remote storage cluster:
```
[root@fscc-sr650-12 dynamic2]# mmlscluster

GPFS cluster information
========================
  GPFS cluster name:         ess3000.bda.scale.ibm.com
  GPFS cluster id:           215057217487177715

[root@fscc-sr650-12 dynamic2]# mmlsfs ess3000_1M --uid
flag                value                    description
------------------- ------------------------ -----------------------------------
 --uid              099B6A7A:5EB99721        File system UID

[root@fscc-sr650-12 GPFS]# mmlsfs ess3000_1M -Q --perfileset-quota --filesetdf
flag                value                    description
------------------- ------------------------ -----------------------------------
 --filesetdf        yes                      Fileset df enabled?
 -Q                 user;group;fileset       Quotas accounting enabled
                    user;group;fileset       Quotas enforced
                    none                     Default quotas enabled
 --perfileset-quota no                       Per-fileset quota enforcement

[root@fscc-sr650-12 GPFS]# mmlsconfig enforceFilesetQuotaOnRoot
enforceFilesetQuotaOnRoot yes  

[root@fscc-sr650-12 GPFS]# mmlsconfig controlSetxattrImmutableSELinux
controlSetxattrImmutableSELinux yes  

[root@fscc-sr650-12 dynamic2]# ls -al /gpfs/ess3000_1M/
total 262
drwxr-xr-x. 13 root       root       262144 Aug 30 13:42 .
drwxr-xr-x.  5 root       root           62 Apr 14 22:42 ..
drwxrwxrwx.  2 root       root         4096 Aug 30 11:37 nfs-export

[root@fscc-sr650-12 dynamic2]# ls -al /gpfs/ess3000_1M/nfs-export/
total 258
drwxrwxrwx.  2 root root   4096 Aug 30 14:33 .
drwxr-xr-x. 13 root root 262144 Aug 30 13:42 ..
-rw-r--r--.  1 root root   1148 Aug 25 19:00 fstab
-rw-r--r--.  1 root root    158 Aug 25 19:00 hosts
-rw-rw-rw-.  1 root root      0 Aug 30 11:37 readall

```

1. Create a static PV pv000 for that GPFS root directory (mounted at /mnt/fs1 with CNSA 5.1.1.1):

We create a static PV for the directory */mnt/fs1* on CNSA which is backed by a remote filesystem */gpfs/ess3000_1M* on a remote storage cluster.
In order to allow a direct binding between the PVC and the specific PV holding the specific data we make use of *Kubernetes labels* and use a *faked* storage class name "static" which is used as some sort of annotation or identifier rather than a real storage class (which it isn't) - this prevents that the default storage class (if any should be defined) is applied instead rather than matching the specific PV from the pool of statically provisioned PVs with the PVC and its specific labels (in case the storage class is omitted in the PVC). 
```
[gero@oc6314270534]$ cat pv000.yaml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv000
  labels:
    product: ibm-spectrum-scale
    type: test
spec:
  storageClassName: static
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: spectrumscale.csi.ibm.com
    volumeHandle: "17399599334533218545;099B6A7A:5EB99721;path=/mnt/fs1"

[gero@oc6314270534]$ oc apply -f pv000.yaml 
persistentvolume/pv000 created

[gero@oc6314270534]$ oc get pv
NAME                             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                                         STORAGECLASS                  REASON   AGE
pv000                            100Gi      RWX            Retain           Available                                                                 static                                 3s
```

2. Create PVC for that volume

The following PVC achieves a direct 1:1 match between the claim and the specifc PV created above with the *labels* and the faked *storage class name* as selectors:
```
[gero@oc6314270534]$ cat pvc000.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc000
spec:
  storageClassName: static
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector: 
    matchLabels:
      product: ibm-spectrum-scale
      type: test

[gero@oc6314270534]$ oc apply -f pvc000.yaml 
persistentvolumeclaim/pvc000 created

[gero@oc6314270534]$ oc get pvc
NAME     STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc000   Bound    pv000    100Gi      RWX            static         4s
```
3. Create pod as user with cluster-admin role 
```
[gero@oc6314270534]$ cat pod.yaml 
kind: Pod
apiVersion: v1
metadata:
  name: pod
spec:
  containers:
    - name: test
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do echo $(hostname) $(date +%Y%m%d-%H:%M:%S) | tee -a /train/train1.log ; sleep 5 ; done;" ]
      volumeMounts:
        - name: vol1
          mountPath: "/data"
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: pvc000

[gero@oc6314270534]$ oc apply -f pod.yaml 
pod/pod created

[gero@oc6314270534]$ oc get pods
NAME   READY   STATUS              RESTARTS   AGE
pod    1/1     Running             0          13s
```
4. Verify that access to existing sub-directories is denied by SELinux
```
[gero@oc6314270534]$ oc rsh pod

sh-4.4# id
uid=0(root) gid=0(root) groups=0(root)
sh-4.4# whoami
root

sh-4.4# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         446G   29G  418G   7% /
tmpfs            64M     0   64M   0% /dev
tmpfs           126G     0  126G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
tmpfs           126G  105M  126G   1% /etc/hostname
fs1              15T  6.5G   15T   1% /data
/dev/sda4       446G   29G  418G   7% /etc/hosts
tmpfs           126G   28K  126G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           126G     0  126G   0% /proc/acpi
tmpfs           126G     0  126G   0% /proc/scsi
tmpfs           126G     0  126G   0% /sys/firmware

sh-4.4# ls -al /data
total 262
drwxr-xr-x. 13 root       root       262144 Aug 30 11:42 .
dr-xr-xr-x.  1 root       root           18 Aug 30 12:10 ..
drwxrwxrwx.  2 root       root         4096 Aug 30 09:37 nfs-export

# Read/Write access to mount point /data is granted
sh-4.4# touch /data/testfile
sh-4.4# ls -al /data/                  
total 262
drwxr-xr-x. 13 root       root       262144 Aug 30 12:11 .
dr-xr-xr-x.  1 root       root           18 Aug 30 12:10 ..
-rw-r--r--.  1 root       root            0 Aug 30 12:11 testfile
drwxrwxrwx.  2 root       root         4096 Aug 30 09:37 nfs-export
sh-4.4# rm /data/testfile 

# Read/Write access to existing sub-directory under mount point /data is denied by SELinux
sh-4.4# ls -al /data/nfs-export/
ls: cannot open directory '/data/nfs-export/': Permission denied
sh-4.4# cat /data/nfs-export/hosts
cat: /data/nfs-export/hosts: Permission denied
sh-4.4# cat /data/nfs-export/hostss
cat: /data/nfs-export/hostss: No such file or directory
sh-4.4# cat /data/nfs-export/readall
cat: /data/nfs-export/readall: Permission denied
sh-4.4# ls -al /data/nfs-export/readall
ls: cannot access '/data/nfs-export/readall': Permission denied

sh-4.4# stat /data/
  File: /data/
  Size: 262144    	Blocks: 512        IO Block: 262144 directory
Device: 100039h/1048633d	Inode: 3           Links: 13
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-08-30 12:11:52.072513451 +0000
Modify: 2021-08-30 12:11:58.880299000 +0000
Change: 2021-08-30 12:11:58.880299000 +0000
 Birth: -

sh-4.4# stat /data/nfs-export/
  File: /data/nfs-export/
  Size: 4096      	Blocks: 1          IO Block: 262144 directory
Device: 100039h/1048633d	Inode: 19456       Links: 2
Access: (0777/drwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-08-30 09:38:09.693424826 +0000
Modify: 2021-08-30 09:37:56.904677000 +0000
Change: 2021-08-30 09:37:56.904677000 +0000
 Birth: -

sh-4.4# ls -al /data/nfs-export/
ls: cannot open directory '/data/nfs-export/': Permission denied

sh-4.4# cat /data/nfs-export/hosts
cat: /data/nfs-export/hosts: Permission denied
```
5. Check the SELinux logs on the OpenShift worker node where pod is running
```
[gero@oc6314270534]$ oc get pods -o wide
NAME   READY   STATUS    RESTARTS   AGE     IP             NODE                          NOMINATED NODE   READINESS GATES
pod    1/1     Running   0          3m19s   10.130.2.181   worker04.ocp4.scale.ibm.com   <none>           <none>

root@worker04 core]# aureport -a

AVC Report
===============================================================
# date time comm subj syscall class permission obj result event
===============================================================
41. 08/30/2021 12:11:11 ls system_u:system_r:container_t:s0:c20,c25 257 dir read unconfined_u:object_r:unlabeled_t:s0 denied 281388
42. 08/30/2021 12:11:16 ls system_u:system_r:container_t:s0:c20,c25 257 dir read system_u:object_r:unlabeled_t:s0 denied 281389
43. 08/30/2021 12:11:23 cat system_u:system_r:container_t:s0:c20,c25 257 file read system_u:object_r:unlabeled_t:s0 denied 281391
44. 08/30/2021 12:11:30 sh system_u:system_r:container_t:s0:c20,c25 257 dir read system_u:object_r:unlabeled_t:s0 denied 281392
45. 08/30/2021 12:11:33 cat system_u:system_r:container_t:s0:c20,c25 257 file read unconfined_u:object_r:unlabeled_t:s0 denied 281393
46. 08/30/2021 12:12:17 ls system_u:system_r:container_t:s0:c20,c25 257 dir read system_u:object_r:unlabeled_t:s0 denied 281397
47. 08/30/2021 12:12:24 cat system_u:system_r:container_t:s0:c20,c25 257 file read system_u:object_r:unlabeled_t:s0 denied 281438

[root@worker04 core]# ausearch -m avc | tail -20
----
time->Mon Aug 30 12:11:30 2021
type=PROCTITLE msg=audit(1630325490.681:281392): proctitle="/bin/sh"
type=SYSCALL msg=audit(1630325490.681:281392): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=564bd8f6e290 a2=90800 a3=0 items=0 ppid=2508113 pid=2508123 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=4294967295 comm="sh" exe="/usr/bin/bash" subj=system_u:system_r:container_t:s0:c20,c25 key=(null)
type=AVC msg=audit(1630325490.681:281392): avc:  denied  { read } for  pid=2508123 comm="sh" name="nfs-export" dev="gpfs" ino=19456 scontext=system_u:system_r:container_t:s0:c20,c25 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=0
----
time->Mon Aug 30 12:11:33 2021
type=PROCTITLE msg=audit(1630325493.138:281393): proctitle=2F7573722F62696E2F636F72657574696C73002D2D636F72657574696C732D70726F672D73686562616E673D636174002F7573722F62696E2F636174002F646174612F6E66732D6578706F72742F72656164616C6C
type=SYSCALL msg=audit(1630325493.138:281393): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=7ffd810e6e06 a2=0 a3=0 items=0 ppid=2508123 pid=2509511 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=4294967295 comm="cat" exe="/usr/bin/coreutils" subj=system_u:system_r:container_t:s0:c20,c25 key=(null)
type=AVC msg=audit(1630325493.138:281393): avc:  denied  { read } for  pid=2509511 comm="cat" name="readall" dev="gpfs" ino=66048 scontext=system_u:system_r:container_t:s0:c20,c25 tcontext=unconfined_u:object_r:unlabeled_t:s0 tclass=file permissive=0
----
time->Mon Aug 30 12:12:17 2021
type=PROCTITLE msg=audit(1630325537.086:281397): proctitle=2F7573722F62696E2F636F72657574696C73002D2D636F72657574696C732D70726F672D73686562616E673D6C73002F7573722F62696E2F6C73002D616C002F646174612F6E66732D6578706F72742F
type=SYSCALL msg=audit(1630325537.086:281397): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=55e0aab62820 a2=90800 a3=0 items=0 ppid=2508123 pid=2510912 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=4294967295 comm="ls" exe="/usr/bin/coreutils" subj=system_u:system_r:container_t:s0:c20,c25 key=(null)
type=AVC msg=audit(1630325537.086:281397): avc:  denied  { read } for  pid=2510912 comm="ls" name="nfs-export" dev="gpfs" ino=19456 scontext=system_u:system_r:container_t:s0:c20,c25 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=0
----
time->Mon Aug 30 12:12:24 2021
type=PROCTITLE msg=audit(1630325544.123:281438): proctitle=2F7573722F62696E2F636F72657574696C73002D2D636F72657574696C732D70726F672D73686562616E673D636174002F7573722F62696E2F636174002F646174612F6E66732D6578706F72742F686F737473
type=SYSCALL msg=audit(1630325544.123:281438): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=7fff423cee08 a2=0 a3=0 items=0 ppid=2508123 pid=2511180 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=4294967295 comm="cat" exe="/usr/bin/coreutils" subj=system_u:system_r:container_t:s0:c20,c25 key=(null)
type=AVC msg=audit(1630325544.123:281438): avc:  denied  { read } for  pid=2511180 comm="cat" name="hosts" dev="gpfs" ino=26112 scontext=system_u:system_r:container_t:s0:c20,c25 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=0
```
It appears we have full RW access to the root or first level of the file system backed by the static PV (/mnt/fs1) but we do not have any access to existing sub-directories in that directory /mnt/fs1/nfs-export). Even if the sub-directory's permissions is set to *chmod 777*.  
Here, the statically provisioned PV is backed by the directory */mnt/fs1* in IBM Spectrum Scale which holds the sub-directory "nfs-export".

**Expected behavior**
When using static provisioning with IBM Spectrum Scale CSI to grant access to an existing directory (i.e. existing data) in IBM Spectrum Scale then it is expected that access to the sub-directories in that directory is available and not prevented by SELinux (as long as the file system UID/GID permissions allow it). 

**Environment**
```
OpenShift Cluster w/CNSA:
 
CNSA v5.1.1.1
CSI v2.2.0

[gero@oc6314270534]$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.7.19    True        False         49d     Cluster version is 4.7.19

Storage cluster:

[root@fscc-sr650-12 dynamic2]# mmdiag
Current GPFS build: "5.1.1.2 ".
Built on Jul  1 2021 at 16:02:28

[root@fscc-sr650-12]# rpm -qa | grep gpfs
gpfs.gskit-8.0.55-19.x86_64
gpfs.crypto-5.1.1-2.x86_64
gpfs.docs-5.1.1-2.noarch
gpfs.gnr-5.1.1-2.x86_64
gpfs.gnr.base-1.0.0-0.x86_64
gpfs.gss.pmcollector-5.1.1-2.el8.x86_64
gpfs.msg.en_US-5.1.1-2.noarch
gpfs.adv-5.1.1-2.x86_64
gpfs.gui-5.1.1-2.noarch
gpfs.gss.pmsensors-5.1.1-2.el8.x86_64
gpfs.base-5.1.1-2.x86_64
gpfs.gpl-5.1.1-2.noarch
gpfs.afm.cos-1.0.0-3.x86_64
gpfs.license.dmd-5.1.1-2.x86_64
gpfs.java-5.1.1-2.x86_64
gpfs.compression-5.1.1-2.x86_64
```

**Comment by gfschmidt** [comment]
It seems that access to the sub-directories of a statically provisioned PV is _not_ prevented by SELinux if the static PV itself is not backed by the root fileset of an IBM Spectrum Scale file system directly (e.g. mounted at /mnt/fs1). 

If the static PV is instead backed  by a sub-directory located *under* the IBM Spectrum Scale file system's root directory (e.g. /mnt/fs1/nfs-export) then access to sub-directories in that directory works as expected and is not prevented by SELinux.

For example, if we only want to grant access to a sub-directory */mnt/fs1/nfs-export* in IBM Spectrum Scale and not to the entire IBM Spectrum Scale file system mounted at */mnt/fs1* and all its sub-directories then it seems to work ok.

With a static PV backed by a sub-directory /mnt/fs1/nfs-export in IBM Spectrum Scale
```
[gero@oc6314270534]$ cat pv000.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv000
  labels:
    product: ibm-spectrum-scale
    type: test
spec:
  storageClassName: static
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: spectrumscale.csi.ibm.com
    volumeHandle: "17399599334533218545;099B6A7A:5EB99721;path=/mnt/fs1/nfs-export"
```
and a PVC
```
[gero@oc6314270534]$ cat pvc000.yaml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc000
spec:
  storageClassName: static
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector: 
    matchLabels:
      product: ibm-spectrum-scale
      type: test
``` 
mounted in the pod at /data/fs1/nfs-export
```
[gero@oc6314270534]$ cat pod.yaml 
kind: Pod
apiVersion: v1
metadata:
  name: pod
spec:
  containers:
    - name: test
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do echo $(hostname) $(date +%Y%m%d-%H:%M:%S) | tee -a /train/train1.log ; sleep 5 ; done;" ]
      volumeMounts:
        - name: vol1
          mountPath: "/data/fs1/nfs-export"
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: pvc000
```
we have full access to all sub-directories and their files of this backing directory:
```
[gero@oc6314270534]$ oc rsh pod
sh-4.4# id
uid=0(root) gid=0(root) groups=0(root)

sh-4.4# ls -al /data/fs1/nfs-export/
total 3
drwxrwxrwx. 4 root root 4096 Aug 30 13:57 .
drwxr-xr-x. 3 root root   24 Aug 30 14:03 ..
drwxrwxrwx. 2 root root 4096 Aug 30 13:59 dir1
drwxr-xr-x. 2 root root 4096 Aug 30 13:58 dir2
-rw-r--r--. 1 root root 1148 Aug 25 17:00 fstab
-rw-r--r--. 1 root root  158 Aug 25 17:00 hosts
-rw-rw-rw-. 1 root root    0 Aug 30 09:37 readall

sh-4.4# ls -al /data/fs1/nfs-export/dir1
total 2
drwxrwxrwx. 2 root root 4096 Aug 30 13:59 .
drwxrwxrwx. 4 root root 4096 Aug 30 13:57 ..
-rw-r--r--. 1 root root  547 Aug 30 13:58 config
-rwxrwxrwx. 1 root root  451 Aug 30 13:59 crontab

sh-4.4# ls -al /data/fs1/nfs-export/dir2
total 2
drwxr-xr-x. 2 root root 4096 Aug 30 13:58 .
drwxrwxrwx. 4 root root 4096 Aug 30 13:57 ..
-rw-r--r--. 1 root root  547 Aug 30 13:58 config
sh-4.4# tail -1 /data/fs1/nfs-export/dir1/config 
```

It seems that SELinux prevents access to sub-directories of the backing directory in a statically provisioned PV only in case the static PV's volumeHandle (e.g. "17399599334533218545;099B6A7A:5EB99721;path=/mnt/fs1") is pointing directly to the root fileset of an IBM Spectrum Scale file system (i.e. the root of an entire IBM Spectrum Scale file system).

In this case when granting access to an entire IBM Spectrum Scale file system with a statically provisioned PV (e.g. path=/mnt/fs1) the expected behavior would be to have full access to all sub-directories as determined by the individual file system permissions and access not to be prevented by SELinux on the worker nodes.
