### ISSUE TITLE
ability to specify multiple rest API point for GUI in CR when It is not supported

### ISSUE THREAD

**Issue by vrushch** [IBM/ibm-spectrum-scale-csi#517]
**Describe the bug**
In cr file,  for each cluster we need to define guiHost under restApi.
```
      restApi:
        - guiHost: "< Primary cluster GUI IP/Hostname >"
```
but this restApi field is defined as dict, this causes issue. 
As customer can define multiple guiHost
```
      restApi:
        - guiHost: "< Primary cluster GUI IP/Hostname >"
        - guiHost: "< Primary cluster GUI IP/Hostname >"
        - guiHost: "< Primary cluster GUI IP/Hostname >"
```

### Issue with Operator Hub console IBM Spectrum Scale CSI Driver creation
User gets prompt under restApi field to add more than 1 guiHost.
This could causes issues and send wrong signal that we are supporting multiple gui's.

**Expected behavior**
User should be able to specify only one GUI host in cr.
