### ISSUE TITLE
inodeLimit change for primaryFset in custom object does not update inodeLimit

### ISSUE THREAD

**Issue by vrushch** [IBM/ibm-spectrum-scale-csi#538]
**Describe the bug**
when we change inodeLimit for primaryFset while operator and driver is running, inodelimit is not getting updated on spectrum scale

**To Reproduce**
1. Running operator and driver with following parameters
```
 clusters:
    - id: "6551742611889582127"
      secrets: "secret1"
      secureSslMode: false
      primary:
        primaryFs: "fs1"
        inodeLimit: "100000" 
        - guiHost: "gui_host"
  ```
2. edit inodeLimit field in cr file and apply
``` 
 clusters:
    - id: "6551742611889582127"
      secrets: "secret1"
      secureSslMode: false
      primary:
        primaryFs: "fs1"
        inodeLimit: "200000" 
        - guiHost: "gui_host"
```

3. check fileset inode limit set for primaryFset , Its not getting changed

**Expected behavior**
fileset inode limit should get updated for primaryFset

**Environment**
Please run the following an paste your output here:
``` bash
# Deployment
[root@remote-csi-master yamls]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
[root@remote-csi-master yamls]#

[root@remote-csi-worker-2 ~]# rpm -qa | grep gpfs
gpfs.msg.en_US-5.1.2-1.noarch
gpfs.adv-5.1.2-1.x86_64
gpfs.gpl-5.1.2-1.noarch
gpfs.afm.cos-1.0.0-4.x86_64
gpfs.librdkafka-5.1.2-1.el7.x86_64
gpfs.java-5.1.2-1.x86_64
gpfs.base-5.1.2-1.x86_64
gpfs.license.adv-5.1.2-1.x86_64
gpfs.crypto-5.1.2-1.x86_64
gpfs.gskit-8.0.55-19.1.x86_64
gpfs.docs-5.1.2-1.noarch
gpfs.compression-5.1.2-1.x86_64
gpfs.gss.pmsensors-5.1.2-1.el7.x86_64
[root@remote-csi-worker-2 ~]#
```
