### ISSUE TITLE
Not able to deploy CSI Driver through OLM Console.

### ISSUE THREAD

**Issue by vrushch** [IBM/ibm-spectrum-scale-csi#555]
## Describe the bug
I am not able to deploy CSI Driver through OLM Console due to following issues.
1. As PrimaryFs is required field. not able to create IBM Spectrum Scale CSI Driver instance due to remote cluster info in clusters do not have PrimaryFS. 
In crd file
```
                      required:
                      - primaryFs
```

2. As primaryFset is getting spectrum-scale-csi-volume-store value assigned. remote cluster's primaryFset is also being set to spectrum-scale-csi-volume-store. and driver fails with
```
E0111 17:39:20.743197       1 gpfs.go:164] Error in plugin initialization: one or more issue found in Spectrum scale csi driver configuration, check Spectrum Scale csi driver logs
F0111 17:39:20.743202       1 main.go:70] Failed to initialize Scale CSI Driver: one or more issue found in Spectrum scale csi driver configuration, check Spectrum Scale csi driver logs
```

In crd file
```
                        primaryFset:
                          default: spectrum-scale-csi-volume-store
                          description: The name of the primary fileset, created in primaryFs
                          type: string
```

3. Same issue as 2nd point with inodeLimit
as default inodeLimit is set for remote cluster, driver asks for primaryFs in remote cluster info provided
```
                        inodeLimit:
                          default: 1M
                          description: Inode limit for Primary Fileset
                          type: string
 ```
3. Driver Registrar sidecar image should not be configurable from additional settings. As other sidecar images cannot be configured from there.
