### ISSUE TITLE
CreateSnapshot fails with error :-"rpc error: code = Internal desc = CreateSnapshot - unable to get mount info for FS [fs1] in primary cluster"

### ISSUE THREAD

**Issue by Pratibhajoshi** [IBM/ibm-spectrum-scale-csi#627]
Describe the bug

seeing this issue in both ways-

1> without tier option
2> with 'tier' option (system default pool/other pool)

How to Reproduce?

**Comment by Pratibhajoshi** [comment]
**Describe the bug**

**CreateSnapshot fails with error :-"rpc error: code = Internal desc = CreateSnapshot - unable to get mount info for FS [fs1] in primary cluster"**

**seeing this issue in both ways-**

1> without tier option
2> with 'tier' option (system default pool/other pool)

**How to Reproduce?**

fs1 filesystem is mounted on CNSA 5.1.3.0 with name remote-sample

**CSI image is at level :-**
```

[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# oc get pods -o yaml | grep imageID | grep csi-driver
      imageID: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:a85cbd5d4ff9f1fe95e90d6ad8a030016bf4907bf1ec3e44a89855cddf0ea933
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]#

[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# oc get pods -o yaml | grep imageID | grep csi-operator
      imageID: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:1a74a2b5f004671c090ab9ea37e0cf69e5b83222c6291f1e30b971fa4bb0f2ea
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]#
```



**How to Reproduce?**

1>create storage class .
2> create pvc
3> create pod and write the data into the same.
4> create volsnapclass
5> perform volsnap
6> create pvc from volsnap - pvcfrmsnap



```
[```
root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# cat sc-291491-dup.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-advance-291491-dup
provisioner: spectrumscale.csi.ibm.com
parameters:
   volBackendFs: "remote-sample"
   version: "2"
reclaimPolicy: Delete
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# cat pvc-291491-dup.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scale-advance-pvc-291491-dup
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibm-spectrum-scale-csi-advance-291491-dup
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# cat pod-291491-dup.yaml
apiVersion: v1
kind: Pod
metadata:
  name: csi-scale-fsetdemo-pod-291491-dup
  labels:
    app: nginx
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - name: mypvc
         mountPath: /usr/share/nginx/html/scale
     ports:
     - containerPort: 80
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: scale-advance-pvc-291491-dup
       readOnly: false
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# cat volsnapclass-291491-dup.yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ibm-spectrum-scale-snapshotclass-advance-291491-dup
driver: spectrumscale.csi.ibm.com
parameters:
  snapWindow: "15"
#Optional : Time in minutes (default=30)
deletionPolicy: Delete
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# cat volsnap-291491-dup.yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ibm-spectrum-scale-snapshot-291491-dup
spec:
  volumeSnapshotClassName: ibm-spectrum-scale-snapshotclass-advance-291491-dup
  source:
    persistentVolumeClaimName: scale-advance-pvc-291491-dup
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# cat pvcfrmsnap-291491-dup.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibm-spectrum-scale-pvc-from-snapshot-291491-dup
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibm-spectrum-scale-storageclass-advance-291491-dup
  dataSource:
    name: ibm-spectrum-scale-snapshot-291491-dup
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]#
```



```
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# oc get sc | grep dup
ibm-spectrum-scale-csi-advance-291491-dup          spectrumscale.csi.ibm.com      Delete          Immediate              false                  95m



[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# oc get pvc | grep dup
ibm-spectrum-scale-pvc-from-snapshot-291491-dup   Pending                                                                        ibm-spectrum-scale-storageclass-advance-291491-dup   86m
scale-advance-pvc-291491-dup                      Bound     pvc-b8e7ad37-334a-4c13-909f-d82e5c00dc97   1Gi        RWX            ibm-spectrum-scale-csi-advance-291491-dup            94m
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]#






error from logs shows as -



[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# oc get volumesnapshot
NAME                                     READYTOUSE   SOURCEPVC                       SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS                                         SNAPSHOTCONTENT                                    CREATIONTIME   AGE
ibm-spectrum-scale-snapshot-291491-dup   false        scale-advance-pvc-291491-dup                                          ibm-spectrum-scale-snapshotclass-advance-291491-dup   snapcontent-639f7bde-877d-4069-aaa2-743545b36179                  89m

[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]#

```



```
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# oc describe volumesnapshot ibm-spectrum-scale-snapshot-291491-dup
Name:         ibm-spectrum-scale-snapshot-291491-dup
Namespace:    ibm-spectrum-scale-csi
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2022-02-21T09:52:04Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:  1
  Managed Fields:
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:source:
          .:
          f:persistentVolumeClaimName:
        f:volumeSnapshotClassName:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-02-21T09:52:04Z
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection":
          v:"snapshot.storage.kubernetes.io/volumesnapshot-bound-protection":
      f:status:
        .:
        f:boundVolumeSnapshotContentName:
        f:error:
          .:
          f:message:
          f:time:
        f:readyToUse:
    Manager:         snapshot-controller
    Operation:       Update
    Time:            2022-02-21T09:52:08Z
  Resource Version:  12555843
  UID:               639f7bde-877d-4069-aaa2-743545b36179
Spec:
  Source:
    Persistent Volume Claim Name:  scale-advance-pvc-291491-dup
  Volume Snapshot Class Name:      ibm-spectrum-scale-snapshotclass-advance-291491-dup
Status:
  Bound Volume Snapshot Content Name:  snapcontent-639f7bde-877d-4069-aaa2-743545b36179
  Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume 1;1;10790403191590936331;0B040B0A:6204F0B0;ibm-spectrum-scale-csi;pvc-b8e7ad37-334a-4c13-909f-d82e5c00dc97;/mnt/remote-sample/ibm-spectrum-scale-csi/pvc-b8e7ad37-334a-4c13-909f-d82e5c00dc97: "rpc error: code = Internal desc = CreateSnapshot - unable to get mount info for FS [fs1] in primary cluster"
    Time:        2022-02-21T09:52:06Z
  Ready To Use:  false
Events:
  Type     Reason                      Age   From                 Message
  ----     ------                      ----  ----                 -------
  Normal   CreatingSnapshot            89m   snapshot-controller  Waiting for a snapshot ibm-spectrum-scale-csi/ibm-spectrum-scale-snapshot-291491-dup to be created by the CSI driver.
  Warning  SnapshotStatusUpdateFailed  15m   snapshot-controller  Snapshot status update failed, snapshot controller failed to update ibm-spectrum-scale-csi/ibm-spectrum-scale-snapshot-291491-dup on API server: etcdserver: request timed out
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]#
```



****data collection and debugging -**

**Verified cluster status , filesystem status , gui pods all looked fine as below -****

```
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# oc get pods -n ibm-spectrum-scale-operator
NAME                                                     READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-controller-manager-5bd9c994b7-ggmqq   1/1     Running   0          18s
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]#


[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# oc get pods -n ibm-spectrum-scale
NAME                               READY   STATUS    RESTARTS   AGE
csi-scale-fsetdemo-pod-291491      1/1     Running   0          3h44m
ibm-spectrum-scale-gui-0           4/4     Running   0          6d1h
ibm-spectrum-scale-gui-1           4/4     Running   0          6d1h
ibm-spectrum-scale-pmcollector-0   2/2     Running   0          6d1h
ibm-spectrum-scale-pmcollector-1   2/2     Running   0          6d1h
master0                            2/2     Running   0          6d1h
master1                            2/2     Running   0          6d1h
master2                            2/2     Running   0          6d1h
worker0                            2/2     Running   0          6d1h
worker1                            2/2     Running   0          6d1h
worker2                            2/2     Running   0          6d1h
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]#


[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]# oc get pods
NAME                                               READY   STATUS             RESTARTS   AGE
csi-scale-fsetdemo-pod-291491-dup                  1/1     Running            0          97m
csi-scale-fsetdemo-pod-291548                      1/1     Running            0          44m
ibm-spectrum-scale-csi-2fg7g                       3/3     Running            0          17m
ibm-spectrum-scale-csi-8kd8n                       3/3     Running            0          17m
ibm-spectrum-scale-csi-attacher-0                  1/1     Running            2          100m
ibm-spectrum-scale-csi-attacher-1                  0/1     CrashLoopBackOff   39         100m
ibm-spectrum-scale-csi-operator-5dcbb798dd-pqmmj   1/1     Running            0          100m
ibm-spectrum-scale-csi-provisioner-0               1/1     Running            1          100m
ibm-spectrum-scale-csi-resizer-0                   1/1     Running            1          100m
ibm-spectrum-scale-csi-snapshotter-0               1/1     Running            1          100m
ibm-spectrum-scale-csi-xckbn                       3/3     Running            0          17m
[root@api.csi250.cp.fyre.ibm.com volsnapshot_testcases]#


sh-4.4# mmlsmount remote-sample -L

File system remote-sample (storage-csi.fyre.ibm.com:fs1) is mounted on 11 nodes:
  10.11.4.11      storage-csi-nsd-1.fyre.ibm.com storage-csi.fyre.ibm.com
  10.11.7.157     storage-csi-nsd-2.fyre.ibm.com storage-csi.fyre.ibm.com
  10.11.7.158     storage-csi-nsd-3.fyre.ibm.com storage-csi.fyre.ibm.com
  10.11.7.160     storage-csi-scalegui.fyre.ibm.com storage-csi.fyre.ibm.com
  10.17.45.35     master1                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.39.38     master0                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.59.122    worker3                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.57.149    worker1                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.48.186    worker0                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.61.34     worker2                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.45.170    master2                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
sh-4.4#



[root@storage-csi-nsd-1 ~]# mmlsfs fs1
flag                value                    description
------------------- ------------------------ -----------------------------------
 -f                 8192                     Minimum fragment (subblock) size in bytes
 -i                 4096                     Inode size in bytes
 -I                 32768                    Indirect block size in bytes
 -m                 1                        Default number of metadata replicas
 -M                 2                        Maximum number of metadata replicas
 -r                 1                        Default number of data replicas
 -R                 2                        Maximum number of data replicas
 -j                 cluster                  Block allocation type
 -D                 nfs4                     File locking semantics in effect
 -k                 nfs4                     ACL semantics in effect
 -n                 32                       Estimated number of nodes that will mount file system
 -B                 4194304                  Block size
 -Q                 user;group;fileset       Quotas accounting enabled
                    user;group;fileset       Quotas enforced
                    none                     Default quotas enabled
 --perfileset-quota Yes                      Per-fileset quota enforcement
 --filesetdf        No                       Fileset df enabled?
 -V                 27.00 (5.1.3.0)          File system version
 --create-time      Thu Feb 10 03:02:08 2022 File system creation time
 -z                 No                       Is DMAPI enabled?
 -L                 33554432                 Logfile size
 -E                 Yes                      Exact mtime mount option
 -S                 relatime                 Suppress atime mount option
 -K                 whenpossible             Strict replica allocation option
 --fastea           Yes                      Fast external attributes enabled?
 --encryption       No                       Encryption enabled?
 --inode-limit      2945024                  Maximum number of inodes in all inode spaces
 --log-replicas     0                        Number of log replicas
 --is4KAligned      Yes                      is4KAligned?
 --rapid-repair     Yes                      rapidRepair enabled?
 --write-cache-threshold 0                   HAWC Threshold (max 65536)
 --subblocks-per-full-block 512              Number of subblocks per full block
 -P                 system;pool1;pool2       Disk storage pools in file system
 --file-audit-log   No                       File Audit Logging enabled?
 --maintenance-mode No                       Maintenance Mode enabled?
 --flush-on-close   No                       flush cache on file close enabled?
 -d                 nsd1;nsd2;nsd21;nsd22    Disks in file system
 -A                 yes                      Automatic mount option
 -o                 none                     Additional mount options
 -T                 /mnt/fs1                 Default mount point
 --mount-priority   0                        Mount priority
[root@storage-csi-nsd-1 ~]#



[root@storage-csi-nsd-1 pvc-de7d48ae-bebc-47bd-b2c3-1a494ae7a67c-Tpool1csi]# mmlsmount fs1 -L

File system fs1 is mounted on 17 nodes:
  10.11.4.11      storage-csi-nsd-1.fyre.ibm.com storage-csi.fyre.ibm.com
  10.11.7.157     storage-csi-nsd-2.fyre.ibm.com storage-csi.fyre.ibm.com
  10.11.7.158     storage-csi-nsd-3.fyre.ibm.com storage-csi.fyre.ibm.com
  10.17.48.186    worker0                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.45.35     master1                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.39.38     master0                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.62.101    worker0                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
  10.17.45.148    master0                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
  10.17.63.101    worker2                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
  10.11.7.160     storage-csi-scalegui.fyre.ibm.com storage-csi.fyre.ibm.com
  10.17.45.170    master2                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.62.182    worker1                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
  10.17.51.157    master1                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
  10.17.61.34     worker2                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.57.149    worker1                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.59.122    worker3                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.54.78     master2                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
[root@storage-csi-nsd-1 pvc-de7d48ae-bebc-47bd-b2c3-1a494ae7a67c-Tpool1csi]#
```
```
