### ISSUE TITLE
Creating multiple volume snapshots using single pvc fails with -  "rpc error: code = Unknown desc = Unable to stat dir ibm-spectrum-scale-csi/.snapshots"

### ISSUE THREAD

**Issue by Pratibhajoshi** [IBM/ibm-spectrum-scale-csi#636]
**Describe the bug**

**seeing this issue -**

1> with 'tier' option (system default pool/other pool)

**How to Reproduce?**

fs1 filesystem is mounted on CNSA 5.1.3.0 with name remote-sample

**CSI image is at level :-**

```
[root@api.csi250.cp.fyre.ibm.com multisnapshots]# oc get pods -o yaml | grep imageID | grep csi-driver
      imageID: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:57532f6b1cdd01176f66be0bf8e45120f0e3f3ffdedeecf34e3e66515cde5890

[root@api.csi250.cp.fyre.ibm.com multisnapshots]# oc get pods -o yaml | grep imageID | grep csi-operator
      imageID: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:04c4b87488e69feca72ad50c384bb210209bbad5ba3d80f5d7de9eb798a4b9b7
[root@api.csi250.cp.fyre.ibm.com multisnapshots]#
```

**How to Reproduce?**

1>create storage class .
2> create pvc
3> create pod and write the data into the same.
4> create volsnapclass
5> perform volsnap
6> create pvc from volsnap - pvcfrmsnap

```
[root@api.csi250.cp.fyre.ibm.com latest]# cat sc-latest.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: sc-latest
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "remote-sample"
    version: "2"
    tier: "pool1"
reclaimPolicy: Delete

[root@api.csi250.cp.fyre.ibm.com latest]# cat pvc-latest.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-latest
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-latest
[root@api.csi250.cp.fyre.ibm.com latest]# cat pod-latest.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-latest
  labels:
    app: nginx
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - name: mypvc
         mountPath: /usr/share/nginx/html/scale
     ports:
     - containerPort: 80
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: pvc-latest
       readOnly: false
```

```
[root@api.csi250.cp.fyre.ibm.com latest]# cat volsnapclass-latest.yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: volsnapclass-latest
driver: spectrumscale.csi.ibm.com
parameters:
  snapWindow: "15"  #Optional : Time in minutes (default=30)
deletionPolicy: Delete
[root@api.csi250.cp.fyre.ibm.com latest]# cat volsnap-latest.yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: volsnap-latest1
spec:
  volumeSnapshotClassName: volsnapclass-latest
  source:
    persistentVolumeClaimName: pvc-latest
[root@api.csi250.cp.fyre.ibm.com latest]# cat pvcfrmsnap-latest.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcfrmsnap-latest-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-latest
  dataSource:
    name: volsnap-latest1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
[root@api.csi250.cp.fyre.ibm.com latest]#


[root@api.csi250.cp.fyre.ibm.com ~]# oc get sc | grep latest
sc-latest                                          spectrumscale.csi.ibm.com      Delete          Immediate              false                  24h
[root@api.csi250.cp.fyre.ibm.com ~]# oc get pvc | grep latest
pvc-latest   Bound    pvc-2fdcd829-50e0-455c-aebf-a70547099be1   1Gi        RWX            sc-latest      35m
[root@api.csi250.cp.fyre.ibm.com ~]# oc get pod | grep latest
pod-latest                                         1/1     Running   0          34m
[root@api.csi250.cp.fyre.ibm.com ~]#


```

```

[root@api.csi250.cp.fyre.ibm.com ~]#  oc get VolumeSnapshotClass | grep latest
volsnapclass-latest                                     spectrumscale.csi.ibm.com   Delete           23h
[root@api.csi250.cp.fyre.ibm.com ~]# oc get VolumeSnapshotContent | grep latest
snapcontent-32c2731f-4994-4b4a-9d9b-2c6c552ae937   false                      Delete           spectrumscale.csi.ibm.com   volsnapclass-latest   volsnap-latest-5   30m
snapcontent-70e1545d-5fe8-485f-a451-f16cc0168856   true         1073741824    Delete           spectrumscale.csi.ibm.com   volsnapclass-latest   volsnap-latest-3   30m
snapcontent-8902fd61-19e2-437c-bf75-2a525ebf4670   true         1073741824    Delete           spectrumscale.csi.ibm.com   volsnapclass-latest   volsnap-latest-4   30m
snapcontent-a3316ef4-d130-4fdb-8535-352af7b49d9a   false                      Delete           spectrumscale.csi.ibm.com   volsnapclass-latest   volsnap-latest-2   30m
snapcontent-b649f2b2-2738-475e-8cb7-a9c0905e092f   true         1073741824    Delete           spectrumscale.csi.ibm.com   volsnapclass-latest   volsnap-latest-1   30m

[root@api.csi250.cp.fyre.ibm.com ~]#  oc get VolumeSnapshot | grep latest
volsnap-latest-1   true         pvc-latest                           1Gi           volsnapclass-latest   snapcontent-b649f2b2-2738-475e-8cb7-a9c0905e092f   31m            31m
volsnap-latest-2   false        pvc-latest                                         volsnapclass-latest   snapcontent-a3316ef4-d130-4fdb-8535-352af7b49d9a                  30m
volsnap-latest-3   true         pvc-latest                           1Gi           volsnapclass-latest   snapcontent-70e1545d-5fe8-485f-a451-f16cc0168856   62s            30m
volsnap-latest-4   true         pvc-latest                           1Gi           volsnapclass-latest   snapcontent-8902fd61-19e2-437c-bf75-2a525ebf4670   16m            30m
volsnap-latest-5   false        pvc-latest                                         volsnapclass-latest   snapcontent-32c2731f-4994-4b4a-9d9b-2c6c552ae937                  30m

[root@api.csi250.cp.fyre.ibm.com ~]# oc get VolumeAttachment
NAME                                                                   ATTACHER                    PV                                         NODE                             ATTACHED   AGE
csi-298244027eafe035a2fb58692834df98aedca3a939a186c664da1403d208fda4   spectrumscale.csi.ibm.com   pvc-cd73ea2a-87f4-403d-8fd8-05c1afe3ae10   worker2.csi250.cp.fyre.ibm.com   true       2d
csi-6efa16116875056f634ca27a370a4dc6015de0135746ff753976fc1fd9424809   spectrumscale.csi.ibm.com   pvc-2fdcd829-50e0-455c-aebf-a70547099be1   worker2.csi250.cp.fyre.ibm.com   true       35m
[root@api.csi250.cp.fyre.ibm.com ~]#



[root@api.csi250.cp.fyre.ibm.com latest]# oc describe VolumeSnapshotClass volsnapclass-latest
Name:             volsnapclass-latest
Namespace:
Labels:           <none>
Annotations:      <none>
API Version:      snapshot.storage.k8s.io/v1
Deletion Policy:  Delete
Driver:           spectrumscale.csi.ibm.com
Kind:             VolumeSnapshotClass
Metadata:
  Creation Timestamp:  2022-02-22T08:34:50Z
  Generation:          1
  Managed Fields:
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:deletionPolicy:
      f:driver:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:parameters:
        .:
        f:snapWindow:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-02-22T08:34:50Z
  Resource Version:  13114111
  UID:               2d9e77cb-0a7e-469e-9672-1a923470a006
Parameters:
  Snap Window:  15
Events:         <none>
[root@api.csi250.cp.fyre.ibm.com latest]#

[root@api.csi250.cp.fyre.ibm.com latest]# oc describe VolumeSnapshot volsnap-latest1
Name:         volsnap-latest1
Namespace:    ibm-spectrum-scale-csi
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2022-02-22T08:35:23Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:  1
  Managed Fields:
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:source:
          .:
          f:persistentVolumeClaimName:
        f:volumeSnapshotClassName:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-02-22T08:35:23Z
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection":
          v:"snapshot.storage.kubernetes.io/volumesnapshot-bound-protection":
      f:status:
        .:
        f:boundVolumeSnapshotContentName:
        f:creationTime:
        f:readyToUse:
        f:restoreSize:
    Manager:         snapshot-controller
    Operation:       Update
    Time:            2022-02-22T08:35:28Z
  Resource Version:  13114320
  UID:               b57a6e99-d3b7-4e65-9a8f-b64f4b9e4465
Spec:
  Source:
    Persistent Volume Claim Name:  pvc-latest
  Volume Snapshot Class Name:      volsnapclass-latest
Status:
  Bound Volume Snapshot Content Name:  snapcontent-b57a6e99-d3b7-4e65-9a8f-b64f4b9e4465
  Creation Time:                       2022-02-22T08:35:24Z
  Ready To Use:                        true
  Restore Size:                        1Gi
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  87m   snapshot-controller  Waiting for a snapshot ibm-spectrum-scale-csi/volsnap-latest1 to be created by the CSI driver.
[root@api.csi250.cp.fyre.ibm.com latest]#
```

**error from logs shows as -**

```
[root@api.csi250.cp.fyre.ibm.com multisnapshots]# oc describe Volumesnapshot volsnap-latest-2
Name:         volsnap-latest-2
Namespace:    ibm-spectrum-scale-csi
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2022-02-23T07:55:14Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:  1
  Managed Fields:
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:source:
          .:
          f:persistentVolumeClaimName:
        f:volumeSnapshotClassName:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-02-23T07:55:14Z
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection":
          v:"snapshot.storage.kubernetes.io/volumesnapshot-bound-protection":
      f:status:
        .:
        f:boundVolumeSnapshotContentName:
        f:error:
          .:
          f:message:
          f:time:
        f:readyToUse:
    Manager:         snapshot-controller
    Operation:       Update
    Time:            2022-02-23T07:55:19Z
  Resource Version:  13694474
  UID:               a3316ef4-d130-4fdb-8535-352af7b49d9a
Spec:
  Source:
    Persistent Volume Claim Name:  pvc-latest
  Volume Snapshot Class Name:      volsnapclass-latest
Status:
  Bound Volume Snapshot Content Name:  snapcontent-a3316ef4-d130-4fdb-8535-352af7b49d9a
  Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume 1;1;10790403191590936331;0B040B0A:6204F0B0;ibm-spectrum-scale-csi;pvc-2fdcd829-50e0-455c-aebf-a70547099be1-Tpool1csi;/mnt/remote-sample/ibm-spectrum-scale-csi/pvc-2fdcd829-50e0-455c-aebf-a70547099be1-Tpool1csi: "rpc error: code = Unknown desc = Unable to stat dir ibm-spectrum-scale-csi/.snapshots/snapshot-b649f2b2-2738-475e-8cb7-a9c0905e092f/pvc-2fdcd829-50e0-455c-aebf-a70547099be1-Tpool1csi."
    Time:        2022-02-23T07:55:19Z
  Ready To Use:  false
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  11s   snapshot-controller  Waiting for a snapshot ibm-spectrum-scale-csi/volsnap-latest-2 to be created by the CSI driver.
[root@api.csi250.cp.fyre.ibm.com multisnapshots]#
```

****data collection and debugging -**

**Verified cluster status , filesystem status , gui pods all looked fine as below -****
```
[root@api.csi250.cp.fyre.ibm.com ~]#  oc get pods -n ibm-spectrum-scale-operator                   NAME                                                    READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-controller-manager-f6bdfff74-hgdf4   1/1     Running   0          27s
[root@api.csi250.cp.fyre.ibm.com ~]#
[root@api.csi250.cp.fyre.ibm.com ~]#
[root@api.csi250.cp.fyre.ibm.com ~]#  oc get pods -n ibm-spectrum-scale                            NAME                               READY   STATUS    RESTARTS   AGE
csi-scale-fsetdemo-pod-291491      1/1     Running   2          2d
ibm-spectrum-scale-gui-0           4/4     Running   0          4h25m
ibm-spectrum-scale-gui-1           4/4     Running   0          4h27m
ibm-spectrum-scale-pmcollector-0   2/2     Running   0          4h27m
ibm-spectrum-scale-pmcollector-1   2/2     Running   0          5h55m
master0                            2/2     Running   0          4h23m
master1                            2/2     Running   0          5h52m
master2                            2/2     Running   0          4h17m
worker0                            2/2     Running   0          5h52m
worker1                            2/2     Running   0          5h52m
worker2                            2/2     Running   0          5h50m
[root@api.csi250.cp.fyre.ibm.com ~]#  oc get pods -n ibm-spectrum-scale-csi
NAME                                               READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-attacher-0                  1/1     Running   0          138m
ibm-spectrum-scale-csi-attacher-1                  1/1     Running   1          138m
ibm-spectrum-scale-csi-bks49                       3/3     Running   0          138m
ibm-spectrum-scale-csi-k4mvp                       3/3     Running   0          138m
ibm-spectrum-scale-csi-lc57p                       3/3     Running   0          138m
ibm-spectrum-scale-csi-operator-85fcf67769-g5dt6   1/1     Running   1          6h3m
ibm-spectrum-scale-csi-provisioner-0               1/1     Running   1          138m
ibm-spectrum-scale-csi-resizer-0                   1/1     Running   0          131m
ibm-spectrum-scale-csi-snapshotter-0               1/1     Running   0          138m
ibm-spectrum-scale-csi-vc568                       3/3     Running   0          138m
ibm-spectrum-scale-csi-vrlf9                       3/3     Running   0          137m
ibm-spectrum-scale-csi-zfxxf                       3/3     Running   0          138m
pod-latest                                         1/1     Running   0          38m
[root@api.csi250.cp.fyre.ibm.com ~]#


sh-4.4# mmlsmount remote-sample -L

File system remote-sample (storage-csi.fyre.ibm.com:fs1) is mounted on 11 nodes:
  10.11.4.11      storage-csi-nsd-1.fyre.ibm.com storage-csi.fyre.ibm.com
  10.11.7.157     `storage-csi-nsd-2.fyre.ibm.com` storage-csi.fyre.ibm.com
  10.11.7.158     storage-csi-nsd-3.fyre.ibm.com storage-csi.fyre.ibm.com
  10.11.7.160     storage-csi-scalegui.fyre.ibm.com storage-csi.fyre.ibm.com
  10.17.45.35     master1                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.39.38     master0                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.59.122    worker3                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.57.149    worker1                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.48.186    worker0                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.61.34     worker2                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.45.170    master2                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
sh-4.4#
```

```
[root@storage-csi-nsd-1 ~]# mmlsfs fs1
flag                value                    description
------------------- ------------------------ -----------------------------------
 -f                 8192                     Minimum fragment (subblock) size in bytes
 -i                 4096                     Inode size in bytes
 -I                 32768                    Indirect block size in bytes
 -m                 1                        Default number of metadata replicas
 -M                 2                        Maximum number of metadata replicas
 -r                 1                        Default number of data replicas
 -R                 2                        Maximum number of data replicas
 -j                 cluster                  Block allocation type
 -D                 nfs4                     File locking semantics in effect
 -k                 nfs4                     ACL semantics in effect
 -n                 32                       Estimated number of nodes that will mount file system
 -B                 4194304                  Block size
 -Q                 user;group;fileset       Quotas accounting enabled
                    user;group;fileset       Quotas enforced
                    none                     Default quotas enabled
 --perfileset-quota Yes                      Per-fileset quota enforcement
 --filesetdf        No                       Fileset df enabled?
 -V                 27.00 (5.1.3.0)          File system version
 --create-time      Thu Feb 10 03:02:08 2022 File system creation time
 -z                 No                       Is DMAPI enabled?
 -L                 33554432                 Logfile size
 -E                 Yes                      Exact mtime mount option
 -S                 relatime                 Suppress atime mount option
 -K                 whenpossible             Strict replica allocation option
 --fastea           Yes                      Fast external attributes enabled?
 --encryption       No                       Encryption enabled?
 --inode-limit      2945024                  Maximum number of inodes in all inode spaces
 --log-replicas     0                        Number of log replicas
 --is4KAligned      Yes                      is4KAligned?
 --rapid-repair     Yes                      rapidRepair enabled?
 --write-cache-threshold 0                   HAWC Threshold (max 65536)
 --subblocks-per-full-block 512              Number of subblocks per full block
 -P                 system;pool1;pool2       Disk storage pools in file system
 --file-audit-log   No                       File Audit Logging enabled?
 --maintenance-mode No                       Maintenance Mode enabled?
 --flush-on-close   No                       flush cache on file close enabled?
 -d                 nsd1;nsd2;nsd21;nsd22    Disks in file system
 -A                 yes                      Automatic mount option
 -o                 none                     Additional mount options
 -T                 /mnt/fs1                 Default mount point
 --mount-priority   0                        Mount priority
[root@storage-csi-nsd-1 ~]#



[root@storage-csi-nsd-1 pvc-de7d48ae-bebc-47bd-b2c3-1a494ae7a67c-Tpool1csi]# mmlsmount fs1 -L

File system fs1 is mounted on 17 nodes:
  10.11.4.11      storage-csi-nsd-1.fyre.ibm.com storage-csi.fyre.ibm.com
  10.11.7.157     storage-csi-nsd-2.fyre.ibm.com storage-csi.fyre.ibm.com
  10.11.7.158     storage-csi-nsd-3.fyre.ibm.com storage-csi.fyre.ibm.com
  10.17.48.186    worker0                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.45.35     master1                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.39.38     master0                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.62.101    worker0                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
  10.17.45.148    master0                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
  10.17.63.101    worker2                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
  10.11.7.160     storage-csi-scalegui.fyre.ibm.com storage-csi.fyre.ibm.com
  10.17.45.170    master2                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.62.182    worker1                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
  10.17.51.157    master1                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
  10.17.61.34     worker2                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.57.149    worker1                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.59.122    worker3                   ibm-spectrum-scale.hci-cluster.cp.fyre.ibm.com
  10.17.54.78     master2                   ibm-spectrum-scale.csi250.cp.fyre.ibm.com
[root@storage-csi-nsd-1 pvc-de7d48ae-bebc-47bd-b2c3-1a494ae7a67c-Tpool1csi]#
```
