### ISSUE TITLE
default value primaryFs: "" removed from remote cluster values in CSIScaleOperator spec.clusters.primary

### ISSUE THREAD

**Issue by vrushch** [IBM/ibm-spectrum-scale-csi#669]
## Describe the bug
Earlier for CSIScaleOperator in CSI with remote cluster
```
  - id: "65517426118895xxxxxx"
    primary:
      inodeLimit: ""
      primaryFs: ""
      primaryFset: ""
    restApi:
    - guiHost: xxxxxx.ibm.com
      guiPort: 443
    secrets: csi-remote-mount-storage-cluster-1
    secureSslMode: false
```
Now , primaryFs: "" got removed
```
  - id: "65517426118895xxxxxx"
    primary:
      inodeLimit: ""
      primaryFset: ""
    restApi:
    - guiHost: xxxxxx.ibm.com
      guiPort: 443
    secrets: csi-remote-mount-storage-cluster-1
    secureSslMode: false
```
This is breaking the automation , as we rely on primaryFs: "" to identify that it is not a primary cluster

## How to Reproduce?
1. Install CSI 2.4.0 and check CSO
2. Install CSI 2.5.0 and check CSO

## Expected behavior
 primaryFs: "" should be added back

Environmental output
```

[root@scale-csi-master functional-tests]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
[root@scale-csi-master functional-tests]#
[root@scale-csi-master functional-tests]# kubectl get pods -o yaml | grep quay
      image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.5.0-070322
      image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.5.0-070322
      imageID: docker-pullable://quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:c61b14b2dd3a2ac7c27187019acf97eb3bae57c1f67a8cea7f8ac069519f9b53
        value: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.5.0-070322
      image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator:v2.5.0-070322
      image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator:v2.5.0-070322
      imageID: docker-pullable://quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:241ab702e62c087b99eb5f2416675bc09b0f1d96365c34b3f292a6ca1429a9e7
      image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.5.0-070322
      image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.5.0-070322
      imageID: docker-pullable://quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:c61b14b2dd3a2ac7c27187019acf97eb3bae57c1f67a8cea7f8ac069519f9b53
[root@scale-csi-master functional-tests]#
```

**Comment by vrushch** [comment]
As discussed with @nitishkumar4 ,
It is caused by following block of code
```
type CSIFilesystem struct {

    // +optional
    // Inode limit for Primary Fileset
    InodeLimit string `json:"inodeLimit"`

    // The name of the primary CSIFilesystem
    PrimaryFs string `json:"primaryFs,omitempty"`

    // +optional
    // The name of the primary fileset, created in primaryFs
    PrimaryFset string `json:"primaryFset"`

    // Remote Spectrum Scale cluster ID
    RemoteCluster string `json:"remoteCluster,omitempty"`
}
```

we are using // +optional with InodeLimit  and PrimaryFset , hence this parameters are shown is CSO

in case of PrimaryFs and RemoteCluster  , we are using omitempty causing this parameters not shown as "" in CSO

**Comment by nitishkumar4** [comment]
@Vrushal PR is merged, please validate if the issue is fixed.

**Comment by vrushch** [comment]
Fixed , output with latest dev image
```
  clusters:
  - id: "1469370384710411xxxx"
    primary:
      primaryFs: fs1
    restApi:
    - guiHost: scale-scalegui
    secrets: local-secret
    secureSslMode: false
  - id: "655174261188958xxxx"
    restApi:
    - guiHost: 10.11.102.xxx
    secrets: remote-secret
    secureSslMode: false
```
Now only applied fields in cr file , will be shown when we describe or edit the CSO
