### ISSUE TITLE
CSO status becomes `Unknown` with Error in operator logs when duplicate values are passed in `spec.tolerations` & `spec.NodeMapping` fields

### ISSUE THREAD

**Issue by nitishkumar4** [IBM/ibm-spectrum-scale-csi#720]
## Describe the bug
CSO status becomes `Unknown` with Error in operator logs when duplicate values are passed in `spec.tolerations` & `spec.NodeMapping` fields. Reconciliation stops. 

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. Add duplicate entry in `spec.NodeMapping`
2. Add duplicate entry in `spec.tolerations`

## Expected behavior

Error handling required for this scenario.

### Data Collection and Debugging

Environmental output

- What openshift/kubernetes version are you running, and the architecture? 
- `kubectl get pods -o wide -n < csi driver namespace> `
- `kubectl get nodes -o wide`
- CNSA/Spectrum Scale version 
- Remote Spectrum Scale version 
- Output for `./tools/spectrum-scale-driver-snap.sh -n < csi driver namespace> -v `

Tool to collect the CSI snap:

`./tools/spectrum-scale-driver-snap.sh -n < csi driver namespace>`

### Add labels

- Component: 
- Severity: Medium
- Customer Impact:
- Customer Probability:
- Phase:

Note : See [labels](https://github.com/IBM/ibm-spectrum-scale-csi/labels) for the labels

**Comment by nitishkumar4** [comment]
RCA: package `mergo.Merge` runs into panic when duplicate values are passed in the CR for `spec.Toleraitons` and `spec.Affinity` fields. This package is used in following files `/opeartor/syncer/csi_node.go` and `/operator/syncer/csi_syncer.go`

Since the code runs in panic state, reconciliation stops and CSO status is updated to `unknown`

**Comment by Jainbrt** [comment]
We have another instance of hit where cso.yaml file has following entries for nodemapping 

```
    nodeMapping:
    - k8sNode: ip-10-0-160-97.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-160-97
    - k8sNode: ip-10-0-222-146.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-222-146
    - k8sNode: ip-10-0-133-143.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-133-143
    - k8sNode: ip-10-0-136-199.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-136-199
    - k8sNode: ip-10-0-195-225.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-195-225
    - k8sNode: ip-10-0-153-243.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-153-243
    - k8sNode: ip-10-0-176-73.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-176-73
    - k8sNode: ip-10-0-187-111.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-187-111
    - k8sNode: ip-10-0-220-152.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-220-152
    - k8sNode: ip-10-0-133-143.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-133-143.ibm-spectrum-scale.ap-northeast-3.compute.internal
    - k8sNode: ip-10-0-136-199.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-136-199.ibm-spectrum-scale.ap-northeast-3.compute.internal
    - k8sNode: ip-10-0-187-111.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-187-111.ibm-spectrum-scale.ap-northeast-3.compute.internal
    - k8sNode: ip-10-0-153-243.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-153-243.ibm-spectrum-scale.ap-northeast-3.compute.internal
    - k8sNode: ip-10-0-176-73.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-176-73.ibm-spectrum-scale.ap-northeast-3.compute.internal
    - k8sNode: ip-10-0-222-146.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-222-146.ibm-spectrum-scale.ap-northeast-3.compute.internal
    - k8sNode: ip-10-0-220-152.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-220-152.ibm-spectrum-scale.ap-northeast-3.compute.internal
    - k8sNode: ip-10-0-160-97.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-160-97.ibm-spectrum-scale.ap-northeast-3.compute.internal
    - k8sNode: ip-10-0-195-225.ap-northeast-3.compute.internal
      spectrumscaleNode: ip-10-0-195-225.ibm-spectrum-scale.ap-northeast-3.compute.internal
```
```
[root@api.jainbrt262.cp.fyre.ibm.com ~]# oc get nodes
NAME                                              STATUS   ROLES          AGE   VERSION
ip-10-0-133-143.ap-northeast-3.compute.internal   Ready    master         14d   v1.23.5+9ce5071
ip-10-0-136-199.ap-northeast-3.compute.internal   Ready    infra,worker   14d   v1.23.5+9ce5071
ip-10-0-153-243.ap-northeast-3.compute.internal   Ready    worker         14d   v1.23.5+9ce5071
ip-10-0-160-97.ap-northeast-3.compute.internal    Ready    infra,worker   14d   v1.23.5+9ce5071
ip-10-0-176-73.ap-northeast-3.compute.internal    Ready    master         14d   v1.23.5+9ce5071
ip-10-0-187-111.ap-northeast-3.compute.internal   Ready    worker         14d   v1.23.5+9ce5071
ip-10-0-195-225.ap-northeast-3.compute.internal   Ready    infra,worker   14d   v1.23.5+9ce5071
ip-10-0-220-152.ap-northeast-3.compute.internal   Ready    worker         14d   v1.23.5+9ce5071
ip-10-0-222-146.ap-northeast-3.compute.internal   Ready    master         14d   v1.23.5+9ce5071
```
