### ISSUE TITLE
Need minor change in error message 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#76]
**Describe the bug**
Need minor change in error message 

**To Reproduce**
1. Create storage class with filesettype and volDirBasePath
```
[root@kube1 fileset]# cat stora.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-fileset
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "gpfs0"
    clusterId: "15492740305828014270"
    filesetType: "dependent"
    volDirBasePath: "8OzgYc"
    uid      : "avahi"
reclaimPolicy: Delete

[root@kube1 fileset]# kubectl apply -f  stora.yaml
storageclass.storage.k8s.io/ibm-spectrum-scale-csi-fileset created
```
2. Create pvc using the above storageclass 
```
[root@kube1 fileset]#  kubectl apply -f pvcfileset.yaml
persistentvolumeclaim/scale-fset-pvc created

[root@kube1 fileset]# kubectl  describe pvc scale-fset-pvc
Name:          scale-fset-pvc
Namespace:     default
StorageClass:  ibm-spectrum-scale-csi-fileset
Status:        Pending
Volume:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"scale-fset-pvc","namespace":"default"},"spec":{"acc...
               volume.beta.kubernetes.io/storage-provisioner: spectrumscale.csi.ibm.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age   From                                                                                                 Message
  Normal   ExternalProvisioning  2s    persistentvolume-controller                                                                          waiting for a volume to be created, either by external provisioner "spectrumscale.csi.ibm.com" or manually created by system administrator
  Normal   Provisioning          2s    spectrumscale.csi.ibm.com_ibm-spectrum-scale-csi-provisioner-0_81e4b731-4d67-11ea-981e-8ad69356e4c7  External provisioner is provisioning volume for claim "default/scale-fset-pvc"
  Warning  ProvisioningFailed    2s    spectrumscale.csi.ibm.com_ibm-spectrum-scale-csi-provisioner-0_81e4b731-4d67-11ea-981e-8ad69356e4c7  failed to provision volume with StorageClass "ibm-spectrum-scale-csi-fileset": rpc error: code = InvalidArgument desc = **fileType** and volDirBasePath must not be specified together in storageClass
```

**Expected behavior**
1. Need minor update in error log where filetype should be replaced with filesetType
2. One more change "failed to provision volume with StorageClass "ibm-spectrum-scale-csi-fileset": rpc error: code = InvalidArgument desc = parentFileset and **fileseType**=independent(Default) must not be specified together in storageClass"
