### ISSUE TITLE
Available data shows negative value for static PVC(OCP UI), on writting data more than available.

### ISSUE THREAD

**Issue by monimeht** [IBM/ibm-spectrum-scale-csi#762]
## Describe the bug
Available data shows negative value for static PVC(OCP UI)

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. Created Static PV using below yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
        name: staticpv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: spectrumscale.csi.ibm.com
    volumeHandle: "0;2;4513801533557814055;B4160B0A:6253B3FC;;;/mnt/remotefs/test"
```
2. Created Static PVC using below yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scale-static-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```
3. Wrote data on /mnt/remotefs/test.
```
root@worker1 /]# cd /mnt/remotefs/test/
[root@worker1 test]# ls
pvc-509a9749-be7e-41fc-b8a4-a938e9b218bf  remotefs
[root@worker1 test]# cd remotefs/
[root@worker1 remotefs]# ls
LW  assets  csi-k8s-local_and_remote_cluster-regression.html  test
```
4. Created pod using below yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: podstatic
  labels:
    app: nginx
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - name: mypvc
         mountPath: /usr/share/nginx/html/scale
     ports:
     - containerPort: 80
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: scale-static-pvc
       readOnly: false
```

```

```
6. Observe the data on OCP UI for Capacity, Used and Available fields. (attached is the screenshot)

## Expected behavior
Negative value for data is not expected in the data fields (available)

### Data Collection and Debugging

Environmental output

```
[root@api.cnsa-moni.cp.fyre.ibm.com yaml]# oc get pvc
NAME                                       STATUS   VOLUME                                          CAPACITY   ACCESS MODES   STORAGECLASS                  AGE
datadir-ibm-spectrum-scale-pmcollector-0   Bound    worker1.cnsa-moni.cp.fyre.ibm.com-pmcollector   25Gi       RWO            ibm-spectrum-scale-internal   47h
datadir-ibm-spectrum-scale-pmcollector-1   Bound    worker0.cnsa-moni.cp.fyre.ibm.com-pmcollector   25Gi       RWO            ibm-spectrum-scale-internal   47h
scale-static-pvc                           Bound    staticpv                                        1Gi        RWX                                          73m
[root@api.cnsa-moni.cp.fyre.ibm.com yaml]# oc get pv
NAME                                            CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                         STORAGECLASS                  REASON   AGE
pvc-039c469f-dd37-4abd-aec9-2918d4e212c5        50Gi       RWX            Delete           Bound    default/pvc1                                                  sc1                                    28h
pvc-31773461-cd22-4904-8a41-04ec06a30dde        50Gi       RWX            Delete           Bound    comp/pvccomp                                                  sccomp                                 27h
pvc-a511c0a4-ea84-4675-ab6e-dcb97350e384        50Gi       RWX            Delete           Bound    comp/pvccomp1                                                 sccomp                                 27h
registry-storage                                200Gi      RWX            Recycle          Bound    openshift-image-registry/image-registry-storage                                                      2d3h
staticpv                                        1Gi        RWX            Retain           Bound    ibm-spectrum-scale/scale-static-pvc              

```

Tool to collect the CSI snap:

`./tools/spectrum-scale-driver-snap.sh -n < csi driver namespace>`

## Screenshots
Find attached the screenshot.

### Add labels

- Component:
- Severity:
- Customer Impact:
- Customer Probability:
- Phase:

Note : See [labels](https://github.com/IBM/ibm-spectrum-scale-csi/labels) for the labels
