### ISSUE TITLE
nodeName mapping problem ?

### ISSUE THREAD

**Issue by hiimheregit** [IBM/ibm-spectrum-scale-csi#809]
Hi guys,

## Describe the bug

We're testing the CSI operator on Openshift with IBM Spectrum Scale. We have successfully installed the Operator through the OperatorHub and also successfully configured it. But, since our node names in Kube don't match our node names in GPFS, we've used nodeMapping :

```yaml
  nodeMapping:
    - k8sNode: worker-0
      spectrumscaleNode: gpfs1
    - k8sNode: worker-1
      spectrumscaleNode: gpfs1
```

Now if I inspect the pod, I see that the healthcheck to the GPFS storage is healthy (and the nodeMapping is indeed working as it should, replacing Kube node worker-0 by the name of our GPFS : 

```bash
$ oc logs ibm-spectrum-scale-csi-6wvq4

I1007 07:58:13.055329       1 http_utils.go:74] http_utils HttpExecuteUserAuth. type: GET, url: https://gpfs1:443/scalemgmt/v2/nodes/gpfs1/health/states?filter=state=HEALTHY,entityType=NODE,component=GPFS, user: [REDACTED]
I1007 07:58:13.075460       1 http_utils.go:44] http_utils UnmarshalResponse. response: &{0x187930 0xc000232740 0x240cd0}
I1007 07:58:13.075620       1 rest_v2.go:43] rest_v2 isStatusOK. statusCode: 200
I1007 07:58:13.075640       1 identityserver.go:70] Probe: GPFS on node gpfs1 is healthy
I1007 07:58:13.075651       1 utils.go:57] GRPC response: ready:<value:true >
```

So far so good. Now the problem appears when I try to attach a volume when running a pipeline (Note : I have generated the PV and PVC manifests using the helper script with the correct values pointing to our GPFS).

Here's the logs on the "attacher" pod :

```bash
$ oc logs ibm-spectrum-scale-csi-attacher-7d5684fb49-5j7hw

I1007 08:05:01.399467       1 connection.go:184] GRPC request: {**"node_id":"worker-1"**,"volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}},"volume_id":"0;2;22222222;AAAAAA:BBBBBB;;labcsi01;/gpfs1/labcsi01"}
I1007 08:05:01.642495       1 connection.go:186] GRPC response: {}
I1007 08:05:01.642588       1 connection.go:187] GRPC error: <nil>
```

The `node_id` has thus been replaced not by the nodeMapping but just retrieving the Kube node name, this behavior can be seen on the DaemonSet config : 

```yaml
# nodeMapping from the Operator config is reflected in env variables
          env:
            - name: worker-0
              value: gpfs1
            - name: worker-1
              value: gpfs1

------

# The args ran by the CSI image 
          args:
            - '--nodeid=$(NODE_ID)'
            - '--endpoint=$(CSI_ENDPOINT)'
------

# The NODE_ID variable comes from

            - name: NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName

# And spec.nodeName on both pods is : 

spec:
  nodeName: worker-0

spec:
  nodeName: worker-1
```

I'm probably not knowledgeable enough on the matter, could you please help me understand this behavior and eventually solve my issue?

## Expected behavior
node_id sent through RPC should be the nodename of the storage and not of the Kube worker.

### Data Collection and Debugging

**Openshift version :** Openshift 4.10
**CSI operator version :** IBM Spectrum Scale CSI Plugin Operator 2.6.0

### Pods

```bash
oc get pods -o wide -n ibm-spectrum-scale-csi-driver

ibm-spectrum-scale-csi-6wvq4                          3/3     Running   0             35m   10.8.38.54     worker-0   <none>           <none>
ibm-spectrum-scale-csi-attacher-7d5684fb49-5j7hw      1/1     Running   3 (35m ago)   19h   10.128.2.98    worker-0   <none>           <none>
ibm-spectrum-scale-csi-attacher-7d5684fb49-7nx46      1/1     Running   1 (67m ago)   18h   10.131.1.168   worker-1   <none>           <none>
ibm-spectrum-scale-csi-operator-66cbc9c78c-pb4j6      1/1     Running   4 (68m ago)   25h   10.131.1.130   worker-1   <none>           <none>
ibm-spectrum-scale-csi-provisioner-cfb78979c-jg8dt    1/1     Running   2 (67m ago)   19h   10.131.1.160   worker-1   <none>           <none>
ibm-spectrum-scale-csi-resizer-bd8cb44c5-6q964        1/1     Running   2 (67m ago)   19h   10.131.1.162   worker-1   <none>           <none>
ibm-spectrum-scale-csi-snapshotter-6bbcfbb6bc-wrcl6   1/1     Running   2 (67m ago)   19h   10.131.1.161   worker-1   <none>           <none>
ibm-spectrum-scale-csi-zvnrm                          3/3     Running   0             67m   10.8.39.54     worker-1   <none>           <none>
```

### Kube nodes

```bash
$ oc get nodes -o wide

NAME       STATUS   ROLES    AGE    VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                                        KERNEL-VERSION                  CONTAINER-RUNTIME
master-0   Ready    master   192d   v1.23.5+3afdacb   10.8.38.52    <none>        Red Hat Enterprise Linux CoreOS 410.84.202206220739-0 (Ootpa)   4.18.0-305.49.1.el8_4.ppc64le   cri-o://1.23.3-6.rhaos4.10.git74543e3.el8
master-1   Ready    master   192d   v1.23.5+3afdacb   10.8.39.52    <none>        Red Hat Enterprise Linux CoreOS 410.84.202206220739-0 (Ootpa)   4.18.0-305.49.1.el8_4.ppc64le   cri-o://1.23.3-6.rhaos4.10.git74543e3.el8
master-2   Ready    master   192d   v1.23.5+3afdacb   10.8.38.53    <none>        Red Hat Enterprise Linux CoreOS 410.84.202206220739-0 (Ootpa)   4.18.0-305.49.1.el8_4.ppc64le   cri-o://1.23.3-6.rhaos4.10.git74543e3.el8
worker-0   Ready    worker   192d   v1.23.5+3afdacb   10.8.38.54    <none>        Red Hat Enterprise Linux CoreOS 410.84.202206220739-0 (Ootpa)   4.18.0-305.49.1.el8_4.ppc64le   cri-o://1.23.3-6.rhaos4.10.git74543e3.el8
worker-1   Ready    worker   192d   v1.23.5+3afdacb   10.8.39.54    <none>        Red Hat Enterprise Linux CoreOS 410.84.202206220739-0 (Ootpa)   4.18.0-305.49.1.el8_4.ppc64le   cri-o://1.23.3-6.rhaos4.10.git74543e3.el8
```

### Images

```bash
$ ./spectrum-scale-driver-snap.sh -n ibm-spectrum-scale-csi-driver -v

Operator Image                : quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator@sha256:b62ad588fbc338090f405740fd8bceaf59b3267cdb532c60ae965643ccae4d5d
Driver Image                  : quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:1efa61d65ee33c574cd2826f1bc6194631b1905996eddaa2ad51b66073e0c409
Node Registrar Image          : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-node-driver-registrar@sha256:4fd21f36075b44d1a423dfb262ad79202ce54e95f5cbc4622a6c1c38ab287ad6
Liveness Probe Image          : us.gcr.io/k8s-artifacts-prod/sig-storage/livenessprobe@sha256:933940f13b3ea0abc62e656c1aa5c5b47c04b15d71250413a6b821bd0c58b94e
Attacher Image                : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-attacher@sha256:8b9c313c05f54fb04f8d430896f5f5904b6cb157df261501b29adc04d2b2dc7b
Provisioner Image             : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-provisioner@sha256:122bfb8c1edabb3c0edd63f06523e6940d958d19b3957dc7b1d6f81e9f1f6119
Snapshotter Image             : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-snapshotter@sha256:89e900a160a986a1a7a4eba7f5259e510398fa87ca9b8a729e7dec59e04c7709
Resizer Image                 : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-resizer@sha256:9ebbf9f023e7b41ccee3d52afe39a89e3ddacdbb69269d583abfc25847cfd9e4

Thanks
