### ISSUE TITLE
Deamonset should not be set with wrong env value 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#855]
## Describe the bug
Deamonset should not be set with wrong env value 

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. Provide wrong loglevel string in VAR_DRIVER_LOGLEVEL such as DEBU#G

```
cat configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: ibm-spectrum-scale-csi-config
  namespace: ibm-spectrum-scale-csi
data:
  VAR_DRIVER_LOGLEVEL: DEBU#G
```

2. wrong value should not be set to env var list, while it should be log an error message in the operator log or event 
```
oc set env ds/ibm-spectrum-scale-csi --list|grep LOG
LOGLEVEL=DEBU#G

```

## Expected behavior
Deamonset should not be set with wrong env value 

### Data Collection and Debugging

Environmental output
```

oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.9.0     True
```
