### ISSUE TITLE
Problem with configuring driver with local and remote clusters

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#87]
@przem123 commented on [Wed Dec 11 2019](https://github.com/IBM/ibm-spectrum-scale-csi-operator/issues/105)

I created a configuration for CSI driver with local and remote cluster. `17399599334479190260` and `gpfs0` are local id and filesystem. `4473793006880872527` is my remote cluster.

```
apiVersion: csi.ibm.com/v1
kind: CSIScaleOperator
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
  name: ibm-spectrum-scale-csi
  release: ibm-spectrum-scale-csi-operator
  namespace: ibm-spectrum-scale-csi-driver
spec:
  clusters:
    - id: '17399599334479190260'
      primary:
        primaryFs: gpfs0
        primaryFset: csifset
      restApi:
        - guiHost: 10.10.1.21
      secrets: csisecret-local
      secureSslMode: false
    - id: '4473793006880872527'
      restApi:
        - guiHost: 10.10.1.52
      secrets: csisecret-remote
      secureSslMode: false
  scaleHostpath: /mnt/gpfs0
status: {}
```
The driver and other items are in `ibm-spectrum-scale-csi-driver`namespace.
```
[root@worker01 operator]# oc get all -n ibm-spectrum-scale-csi-driver
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/ibm-spectrum-scale-csi-attacher-0                  1/1     Running   0          5h12m
pod/ibm-spectrum-scale-csi-kjcs6                       2/2     Running   0          4h46m
pod/ibm-spectrum-scale-csi-nxmkg                       2/2     Running   0          4h46m
pod/ibm-spectrum-scale-csi-operator-75f65c5999-9wnk2   2/2     Running   0          5h58m
pod/ibm-spectrum-scale-csi-provisioner-0               1/1     Running   0          5h12m

NAME                                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/ibm-spectrum-scale-csi-operator-metrics   ClusterIP   172.30.179.144   <none>        8383/TCP   5h58m

NAME                                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/ibm-spectrum-scale-csi   2         2         2       2            2           <none>          5h12m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ibm-spectrum-scale-csi-operator   1/1     1            1           5h58m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/ibm-spectrum-scale-csi-operator-75f65c5999   1         1         1       5h58m

NAME                                                  READY   AGE
statefulset.apps/ibm-spectrum-scale-csi-attacher      1/1     5h12m
statefulset.apps/ibm-spectrum-scale-csi-provisioner   1/1     5h12m
```

Unfortunately, I cannot use it dynamic povisioning for local and remote fs:
```
[root@worker01 operator]# oc describe pvc scale-remotefset-pvc
Name:          scale-remotefset-pvc
Namespace:     default
StorageClass:  ibm-spectrum-scale-csi-remotefs
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: ibm-spectrum-scale-csi
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason                Age                      From                         Message
  ----       ------                ----                     ----                         -------
  Normal     ExternalProvisioning  109s (x1191 over 4h51m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ibm-spectrum-scale-csi" or manually created by system administrator
Mounted By:  <none>
```
 
Any idea how to solve it ?

---

@yadaven commented on [Thu Dec 12 2019](https://github.com/IBM/ibm-spectrum-scale-csi-operator/issues/105#issuecomment-564904589)

I think in storage class we are not using correct provisioner name. Recently it has been changed to `spectrumscale.csi.ibm.com` instead of `ibm-spectrum-scale-csi`

---

@mew2057 commented on [Thu Dec 12 2019](https://github.com/IBM/ibm-spectrum-scale-csi-operator/issues/105#issuecomment-565042126)

@yadaven @smitaraut  Has the documentation in the GitHub Repo and KC been verified to match the provisioner name change? Moving this issue to driver repo.
