### ISSUE TITLE
New configmap collection required in CSI snap

### ISSUE THREAD

**Issue by saurabhwani5** [IBM/ibm-spectrum-scale-csi#894]
## Describe the bug
New configmap  ibm-spectrum-scale-csi-config which is added in CSI 2.9.0 release, should be collected in CSI snap 

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. New configmap Example:
```
[root@saurabh-csi-master dev]# cat configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
 name: ibm-spectrum-scale-csi-config
 namespace: ibm-spectrum-scale-csi-driver
data:
 VAR_DRIVER_LOGLEVEL: TRACE
```
2. If we run CSI snap it won't collect new configmap

## Expected behavior
CSI snap should collect the new configmpa
